// Level exam items, lessons 13-18, written for this app.
EXAM.push(
// ---------- Lesson 13: Umzug und Nachbarn ----------
{ id: "L13-g1", lesson: 13, skill: "grammar", topic: "Wo? + Dativ", type: "mc", q: "Mein Fahrrad steht seit gestern ___ Keller.", opts: ["in den", "ins", "in die", "im"], a: 3, why: "Position (wo?) takes the dative: in dem = im Keller." },
{ id: "L13-g2", lesson: 13, skill: "grammar", topic: "Wohin? + Akkusativ", type: "mc", q: "Wir hängen die Uhr über ___ Tür.", opts: ["die", "der", "den", "dem"], a: 0, why: "Movement to a place (wohin?) takes the accusative: über die Tür." },
{ id: "L13-g3", lesson: 13, skill: "grammar", topic: "legen/liegen, stellen/stehen", type: "mc", q: "Die Zeitung hat den ganzen Tag auf dem Boden ___.", opts: ["gehängt", "gelegen", "gelegt", "gestellt"], a: 1, why: "Position (wo? + dative) uses liegen, Perfekt hat gelegen; gelegt is the action 'put'." },
{ id: "L13-v1", lesson: 13, skill: "vocab", topic: "Flat hunting vocabulary", type: "mc", q: "Die Miete ist 800 Euro, plus 150 Euro ___ für Heizung und Wasser.", opts: ["Anzeige", "Besichtigung", "Nebenkosten", "Kaution"], a: 2, why: "Nebenkosten = extra costs such as heating and water." },
{ id: "L13-w1", lesson: 13, skill: "writing", topic: "stellen vs stehen", type: "gap", q: "Ich ___ die Vase auf den Tisch, und jetzt ___ sie dort. (stellen / stehen)", a: ["stelle", "steht"], why: "stellen = to put (action, + accusative); stehen = to be standing (position)." },
{ id: "L13-w2", lesson: 13, skill: "writing", topic: "Wohin? + Akkusativ", type: "tr", en: "I'm putting the boxes into the cellar.", hint: "use stellen", de: "Ich stelle die Kisten in den Keller.", alt: ["Ich stelle die Kartons in den Keller.", "Die Kisten stelle ich in den Keller.", "Die Kartons stelle ich in den Keller."], why: "Movement into a place: stellen + in den Keller (accusative)." },

// ---------- Lesson 14: Schule und Ausbildung ----------
{ id: "L14-g1", lesson: 14, skill: "grammar", topic: "Präteritum of haben", type: "mc", q: "Als Kinder ___ wir keinen Fernseher.", opts: ["hatte", "hattet", "hattest", "hatten"], a: 3, why: "Präteritum of haben with wir: wir hatten." },
{ id: "L14-g2", lesson: 14, skill: "grammar", topic: "Präteritum of modal verbs", type: "mc", q: "Damals ___ ich mit zwölf noch nicht allein in die Stadt fahren.", opts: ["durfte", "darfte", "durften", "dürfen"], a: 0, why: "Modal Präteritum loses the umlaut: dürfen → ich durfte." },
{ id: "L14-g3", lesson: 14, skill: "grammar", topic: "Perfekt without ge-", type: "mc", q: "Der Lehrer hat uns die Aufgabe zweimal ___.", opts: ["ergeklärt", "erklärt", "geerklärt", "erklären"], a: 1, why: "Verbs with an inseparable prefix (er-) take no ge-: hat erklärt." },
{ id: "L14-v1", lesson: 14, skill: "vocab", topic: "School and training vocabulary", type: "mc", q: "Nach der Schule habe ich drei Monate ein ___ in einem Hotel gemacht.", opts: ["Abitur", "Fach", "Praktikum", "Zeugnis"], a: 2, why: "ein Praktikum machen = to do an internship." },
{ id: "L14-w1", lesson: 14, skill: "writing", topic: "Perfekt of -ieren verbs", type: "gap", q: "Meine Schwester ___ in Jerusalem Medizin ___. (studieren, Perfekt)", a: ["hat", "studiert"], why: "Verbs ending in -ieren have no ge- in the Perfekt: hat studiert." },
{ id: "L14-w2", lesson: 14, skill: "writing", topic: "Präteritum of modal verbs", type: "tr", en: "As a child I had to help my mother every day.", hint: "Präteritum", de: "Als Kind musste ich meiner Mutter jeden Tag helfen.", alt: ["Als Kind musste ich jeden Tag meiner Mutter helfen.", "Ich musste als Kind jeden Tag meiner Mutter helfen.", "Ich musste als Kind meiner Mutter jeden Tag helfen.", "Als Kind musste ich meiner Mama jeden Tag helfen.", "Als Kind musste ich jeden Tag meiner Mama helfen.", "Als Kind musste ich meiner Mutter täglich helfen.", "Ich musste als Kind meiner Mutter täglich helfen."], why: "müssen → musste; helfen takes the dative (meiner Mutter); infinitive at the end." },

// ---------- Lesson 15: Im Büro ----------
{ id: "L15-g1", lesson: 15, skill: "grammar", topic: "weil: verb at the end", type: "mc", q: "Ich bleibe heute länger im Büro, weil ich den Bericht noch ___.", opts: ["muss schreiben", "schreibe muss", "müssen schreiben", "schreiben muss"], a: 3, why: "In a weil-clause the conjugated verb (muss) goes to the very end, after the infinitive." },
{ id: "L15-g2", lesson: 15, skill: "grammar", topic: "dass: separable verb at the end", type: "mc", q: "Der Chef sagt, dass die Besprechung morgen um neun ___.", opts: ["anfängt", "fängt an", "anfangen", "an fängt"], a: 0, why: "In a dass-clause the verb goes to the end and a separable verb joins up again: anfängt." },
{ id: "L15-g3", lesson: 15, skill: "grammar", topic: "dass vs weil", type: "mc", q: "Ich hoffe, ___ Sie mir die Datei heute noch schicken können.", opts: ["und", "dass", "weil", "denn"], a: 1, why: "After verbs of thinking and hoping (hoffen) use dass + verb at the end." },
{ id: "L15-v1", lesson: 15, skill: "vocab", topic: "Phone phrases", type: "mc", q: "Herr Weber ist gerade in einer Besprechung. Soll er Sie später ___?", opts: ["verbinden", "hinterlassen", "zurückrufen", "ausrichten"], a: 2, why: "jemanden zurückrufen = to call someone back." },
{ id: "L15-w1", lesson: 15, skill: "writing", topic: "dass + Perfekt word order", type: "gap", q: "Sie sagt, dass sie die Unterlagen schon ___ ___. (schicken, Perfekt)", a: ["geschickt", "hat/habe"], why: "In a dass-clause the conjugated verb hat comes last, after the participle." },
{ id: "L15-w2", lesson: 15, skill: "writing", topic: "weil-clauses", type: "tr", en: "I'm calling because the printer isn't working.", hint: "use weil", de: "Ich rufe an, weil der Drucker nicht funktioniert.", alt: ["Ich rufe an, weil der Drucker nicht geht.", "Ich rufe an, weil der Drucker nicht funktioniert!"], why: "weil sends the verb (funktioniert) to the end of the clause." },

// ---------- Lesson 16: Gesund leben ----------
{ id: "L16-g1", lesson: 16, skill: "grammar", topic: "Reflexive pronouns", type: "mc", q: "Wir sollten ___ am Wochenende mehr ausruhen.", opts: ["euch", "sich", "mich", "uns"], a: 3, why: "The reflexive pronoun for wir is uns." },
{ id: "L16-g2", lesson: 16, skill: "grammar", topic: "Advice with sollte", type: "mc", q: "Du ___ weniger Kaffee trinken, das ist besser für dich.", opts: ["solltest", "sollte", "solltet", "sollten"], a: 0, why: "sollte with du: du solltest." },
{ id: "L16-g3", lesson: 16, skill: "grammar", topic: "Imperative (du)", type: "mc", q: "___ mir bitte das Salz, Lea!", opts: ["Gebt", "Gib", "Gibst", "Geben"], a: 1, why: "du-imperative: du gibst minus -st = Gib! (the e→i change stays)." },
{ id: "L16-v1", lesson: 16, skill: "vocab", topic: "Health and diet vocabulary", type: "mc", q: "Ich esse kein Fleisch, ich bin ___.", opts: ["ungesund", "fit", "vegetarisch", "schlank"], a: 2, why: "vegetarisch = vegetarian (no meat)." },
{ id: "L16-w1", lesson: 16, skill: "writing", topic: "Reflexive verbs in the Perfekt", type: "gap", q: "Er ___ ___ beim Joggen verletzt. (sich verletzen)", a: ["hat", "sich"], why: "Reflexive verbs form the Perfekt with haben; the pronoun follows the verb: hat sich verletzt." },
{ id: "L16-w2", lesson: 16, skill: "writing", topic: "Advice with sollte", type: "tr", en: "You should go for a walk every day.", hint: "informal you, use sollte", de: "Du solltest jeden Tag spazieren gehen.", alt: ["Jeden Tag solltest du spazieren gehen.", "Du solltest jeden Tag einen Spaziergang machen.", "Jeden Tag solltest du einen Spaziergang machen.", "Du solltest täglich spazieren gehen.", "Du solltest täglich einen Spaziergang machen."], why: "sollte + infinitive at the end: Du solltest … spazieren gehen." },

// ---------- Lesson 17: Kleidung und Mode ----------
{ id: "L17-g1", lesson: 17, skill: "grammar", topic: "Adjective endings after der/die/das", type: "mc", q: "Ich nehme den ___ Mantel.", opts: ["schwarze", "schwarzer", "schwarzes", "schwarzen"], a: 3, why: "After den (accusative masculine) the adjective ends in -en." },
{ id: "L17-g2", lesson: 17, skill: "grammar", topic: "Adjective endings after ein", type: "mc", q: "Sie trägt heute ein ___ Kleid.", opts: ["rotes", "rote", "roten", "roter"], a: 0, why: "ein has no ending, so the adjective shows the neuter: ein rotes Kleid." },
{ id: "L17-g3", lesson: 17, skill: "grammar", topic: "welch- in the dative", type: "mc", q: "Mit ___ Schuhen gehst du zur Hochzeit?", opts: ["welchem", "welchen", "welche", "welcher"], a: 1, why: "mit takes the dative; welch- in the dative plural is welchen." },
{ id: "L17-v1", lesson: 17, skill: "vocab", topic: "Clothes shopping verbs", type: "mc", q: "Ich habe die Schuhe gestern hier gekauft, aber sie sind zu klein. Kann ich sie gegen ein größeres Paar ___?", opts: ["ausziehen", "umziehen", "umtauschen", "anziehen"], a: 2, why: "umtauschen = to exchange goods in a shop." },
{ id: "L17-w1", lesson: 17, skill: "writing", topic: "Adjective endings (der / dein)", type: "gap", q: "Der ___ Pullover passt gut zu deiner ___ Jacke. (blau / weiß)", a: ["blaue", "weißen"], why: "Nominative after der: -e (der blaue); dative after deiner: -en (deiner weißen)." },
{ id: "L17-w2", lesson: 17, skill: "writing", topic: "Adjective endings after ein / no article", type: "tr", en: "Today I'm wearing a striped shirt and black boots.", de: "Heute trage ich ein gestreiftes Hemd und schwarze Stiefel.", alt: ["Ich trage heute ein gestreiftes Hemd und schwarze Stiefel."], why: "ein gestreiftes Hemd (neuter, -es); plural without article: schwarze Stiefel." },

// ---------- Lesson 18: Urlaub planen ----------
{ id: "L18-g1", lesson: 18, skill: "grammar", topic: "Comparative", type: "mc", q: "Die Jugendherberge ist ___ als das Hotel.", opts: ["günstig", "am günstigsten", "mehr günstig", "günstiger"], a: 3, why: "Comparative = adjective + -er + als; German never uses 'mehr' + adjective." },
{ id: "L18-g2", lesson: 18, skill: "grammar", topic: "Superlative", type: "mc", q: "Im Juli ist es auf der Insel am ___.", opts: ["heißesten", "heißsten", "heißeste", "heißer"], a: 0, why: "am … -sten; after ß an e is added: am heißesten." },
{ id: "L18-g3", lesson: 18, skill: "grammar", topic: "wenn-clause first: verb, comma, verb", type: "mc", q: "Wenn wir genug Geld haben, ___ ins Ausland.", opts: ["wir fahren dann", "fahren wir", "wir fahren", "fahren"], a: 1, why: "A wenn-clause in first position counts as position 1, so the main clause starts with the verb." },
{ id: "L18-v1", lesson: 18, skill: "vocab", topic: "Holiday and accommodation vocabulary", type: "mc", q: "Wir haben ein Zimmer mit ___ gebucht: Frühstück und Abendessen sind im Preis enthalten.", opts: ["Abfahrt", "Saison", "Halbpension", "Gepäck"], a: 2, why: "Halbpension = half board (breakfast and dinner)." },
{ id: "L18-w1", lesson: 18, skill: "writing", topic: "Comparative and superlative", type: "gap", q: "Der Zug ist ___ als der Bus, aber das Flugzeug ist am ___. (schnell)", a: ["schneller", "schnellsten"], why: "Comparative -er + als; superlative am … -sten." },
{ id: "L18-w2", lesson: 18, skill: "writing", topic: "wenn-clauses", type: "tr", en: "When I'm on holiday, I sleep longer.", hint: "use wenn", de: "Wenn ich Urlaub habe, schlafe ich länger.", alt: ["Wenn ich im Urlaub bin, schlafe ich länger.", "Ich schlafe länger, wenn ich Urlaub habe.", "Ich schlafe länger, wenn ich im Urlaub bin."], why: "wenn sends its verb to the end; after a wenn-clause the main clause starts with the verb." },

// ---------- Reading ----------
{ id: "L13-r1", lesson: 13, skill: "reading", topic: "Reading: moving and neighbours", type: "mc",
  text: "Hallo Mia, seit zwei Wochen wohnen wir jetzt in der neuen Wohnung im dritten Stock. Leider gibt es keinen Aufzug, und der Umzug war sehr anstrengend! Die Wohnung ist hell und die Straße ist ruhig. Nur unser Nachbar über uns hört abends laute Musik, das stört mich ein bisschen. Viele Kisten stehen noch in der Küche, aber das Sofa steht schon im Wohnzimmer. Hast du am Samstag Zeit? Dann trinken wir zusammen Kaffee. Liebe Grüße, Dana",
  q: "What bothers Dana about the new flat?", opts: ["The street is very noisy.", "The flat is quite dark.", "The sofa doesn't fit in the living room.", "The neighbour upstairs plays loud music in the evening."], a: 3 },
{ id: "L15-r1", lesson: 15, skill: "reading", topic: "Reading: office email", type: "mc",
  text: "Liebe Frau Brandt, leider kann ich morgen nicht zur Besprechung um zehn Uhr kommen, weil ich einen Termin beim Arzt habe. Können wir die Besprechung auf Donnerstag verschieben? Die Unterlagen für das Projekt finden Sie im Anhang. Herr Klein sagt, dass die Präsentation noch nicht fertig ist. Er bereitet sie bis Freitag vor. Sie erreichen mich heute bis 17 Uhr im Büro. Mit freundlichen Grüßen, Jonas Weber",
  q: "What does Jonas write?", opts: ["He wants to move tomorrow's meeting to Thursday.", "He asks Frau Brandt to send him the documents.", "He says the presentation is already finished.", "He can't be reached at the office today."], a: 0 },
{ id: "L17-r1", lesson: 17, skill: "reading", topic: "Reading: buying clothes", type: "mc",
  text: "Hi Paula, ich war heute in der Stadt und habe für die Hochzeit von Ben ein elegantes Kleid gesucht. Im ersten Geschäft war das blaue Kleid zu eng, und das rote war viel zu teuer. Am Ende habe ich ein dunkelgrünes Kleid aus Baumwolle gekauft – es ist sehr bequem! Leider passen meine alten Schuhe nicht dazu. Welche Schuhe soll ich anziehen? Die braunen Stiefel oder deine schwarzen Schuhe? Bis bald, Lara",
  q: "What did Lara buy?", opts: ["New black shoes.", "A dark green cotton dress.", "The blue dress, even though it was tight.", "The expensive red dress."], a: 1 },
{ id: "L18-r1", lesson: 18, skill: "reading", topic: "Reading: comparing holiday offers", type: "mc",
  text: "Familie Levi plant ihren Urlaub im August und vergleicht zwei Angebote. Das Hotel Seeblick liegt direkt am Strand und hat einen Pool, aber eine Übernachtung im Doppelzimmer kostet 180 Euro. Die Ferienwohnung Sonne liegt zehn Minuten vom Strand entfernt. Sie ist größer als das Hotelzimmer und kostet nur 110 Euro pro Nacht. Die Kinder finden das Hotel am schönsten, weil es einen Pool hat. Die Eltern finden die Ferienwohnung besser, weil sie günstiger ist und eine Küche hat.",
  q: "Which statement is true?", opts: ["The children like the holiday flat best.", "The hotel room is bigger than the holiday flat.", "The holiday flat is cheaper than the hotel.", "The holiday flat is right on the beach."], a: 2 },

// ---------- Listening ----------
{ id: "L14-l1", lesson: 14, skill: "listening", topic: "Listening: school days", type: "mc", audio: "Ich konnte die Frage nicht beantworten, weil ich sie nicht verstanden habe.", q: "Why couldn't the speaker answer the question?", opts: ["Because they had forgotten their homework.", "Because the teacher was too strict.", "Because they were ill.", "Because they didn't understand it."], a: 3 },
{ id: "L15-l1", lesson: 15, skill: "listening", topic: "Listening: working from home", type: "mc", audio: "Ich glaube, dass Homeoffice gut ist, weil ich zu Hause ruhiger arbeiten kann.", q: "Why does the speaker think working from home is good?", opts: ["They can work more quietly at home.", "They can sleep longer.", "They don't like their colleagues.", "Their boss works from home too."], a: 0 },
{ id: "L18-l1", lesson: 18, skill: "listening", topic: "Listening: holiday preferences", type: "mc", audio: "Am liebsten fahre ich ans Meer, aber mein Partner wandert lieber.", q: "What does the speaker's partner prefer?", opts: ["Staying at home", "Hiking", "Going to the sea", "Visiting museums"], a: 1 },
{ id: "L13-l1", lesson: 13, skill: "listening", topic: "Dictation: wo? + Dativ", type: "dict", audio: "Das Bild hängt jetzt an der Wand über dem Sofa.", q: "Das Bild hängt jetzt an ___ Wand über dem Sofa.", a: ["der"], why: "Position (wo?) takes the dative: an der Wand." },
{ id: "L17-l1", lesson: 17, skill: "listening", topic: "Dictation: adjective endings after ein", type: "dict", audio: "Im Winter brauche ich einen warmen Mantel und einen dicken Schal.", q: "Im Winter brauche ich einen warmen Mantel und einen ___ Schal.", a: ["dicken"], why: "Accusative masculine after einen: -en (einen dicken Schal)." }
);
