// Level exam items, lessons 19-24, written for this app.
EXAM.push(
// ---------- Lesson 19: Feste und Geschenke ----------
{ id: "L19-g1", lesson: 19, skill: "grammar", topic: "Dativ + Akkusativ objects", type: "mc", q: "Zum Jahrestag schenkt Daniel ___ Frau einen Strauß Rosen.", opts: ["seiner", "seine", "seinem", "seinen"], a: 0, why: "The person who receives is in the Dativ; die Frau becomes seiner Frau." },
{ id: "L19-g2", lesson: 19, skill: "grammar", topic: "Dativ pronouns", type: "mc", q: "Meine Tochter liebt Schmuck. Die Kette gefällt ___ sehr.", opts: ["ihr", "sie", "ihm", "ihn"], a: 0, why: "gefallen takes the Dativ; sie (she) becomes ihr in the Dativ." },
{ id: "L19-g3", lesson: 19, skill: "grammar", topic: "Order of two objects", type: "mc", q: "Das Päckchen ist für Tom. Ich bringe ___ morgen.", opts: ["es ihm", "ihm es", "ihn es", "es ihn"], a: 0, why: "With two pronouns the Akkusativ comes before the Dativ: es ihm." },
{ id: "L19-v1", lesson: 19, skill: "vocab", topic: "Celebrations vocabulary", type: "mc", q: "Mein Mann hat nichts gewusst – die Party war eine große ___.", opts: ["Überraschung", "Stimmung", "Gutschein", "Kerze"], a: 0, why: "He knew nothing, so the party was a surprise (Überraschung)." },
{ id: "L19-w1", lesson: 19, skill: "writing", topic: "Dativ pronouns", type: "gap", q: "Wir haben ___ einen Gutschein geschenkt, und sie hat ___ eine Karte geschrieben. (sie = she, wir)", a: ["ihr", "uns"], why: "The receiver is in the Dativ: sie → ihr, wir → uns." },
{ id: "L19-w2", lesson: 19, skill: "writing", topic: "Order of two objects", type: "tr", en: "I'm showing it to her today.", hint: "it = das Foto", de: "Ich zeige es ihr heute.", alt: ["Heute zeige ich es ihr."], why: "Two pronouns: Akkusativ first, then Dativ (es ihr)." },

// ---------- Lesson 20: Medien und Technik ----------
{ id: "L20-g1", lesson: 20, skill: "grammar", topic: "Indirect questions with ob", type: "mc", q: "Ich frage mich, ___ der alte Laptop noch funktioniert.", opts: ["ob", "wenn", "dass", "was"], a: 0, why: "An indirect yes/no question starts with ob (whether/if), not wenn." },
{ id: "L20-g2", lesson: 20, skill: "grammar", topic: "Indirect W-questions (word order)", type: "mc", q: "Können Sie mir sagen, wann ___?", opts: ["das Geschäft aufmacht", "macht das Geschäft auf", "das Geschäft macht auf", "das Geschäft auf macht"], a: 0, why: "In an indirect question the verb goes to the end, and a separable verb joins together: aufmacht." },
{ id: "L20-g3", lesson: 20, skill: "grammar", topic: "Verbs with prepositions", type: "mc", q: "Meine Tochter interessiert sich sehr ___ Computerspiele.", opts: ["für", "in", "an", "auf"], a: 0, why: "The fixed pair is sich interessieren für + Akkusativ." },
{ id: "L20-v1", lesson: 20, skill: "vocab", topic: "Phone and computer vocabulary", type: "mc", q: "Mein Handy geht gleich aus. Ich muss den ___ aufladen.", opts: ["Akku", "Bildschirm", "Link", "Fehler"], a: 0, why: "You charge (aufladen) the battery: der Akku." },
{ id: "L20-w1", lesson: 20, skill: "writing", topic: "Indirect W-questions (word order)", type: "gap", q: "Weißt du, wie man die App ___? (herunterladen)", a: ["herunterlädt"], why: "The verb goes to the end of the indirect question; the separable verb joins up and laden becomes lädt." },
{ id: "L20-w2", lesson: 20, skill: "writing", topic: "Indirect questions with ob", type: "tr", en: "Do you know if the printer is broken?", hint: "use ob", de: "Weißt du, ob der Drucker kaputt ist?", alt: ["Wissen Sie, ob der Drucker kaputt ist?", "Wisst ihr, ob der Drucker kaputt ist?"], why: "\"if\" here is ob, and the verb goes to the end." },

// ---------- Lesson 21: Kochen und Essen gehen ----------
{ id: "L21-g1", lesson: 21, skill: "grammar", topic: "Sequence words + verb second", type: "mc", q: "Danach ___ die Sahne in den Topf.", opts: ["gibt man", "man gibt", "gibt", "man geben"], a: 0, why: "danach takes position 1, so the verb comes next and the subject follows it." },
{ id: "L21-g2", lesson: 21, skill: "grammar", topic: "Adjective endings without article", type: "mc", q: "Zum Frühstück trinke ich gern ___ Kaffee.", opts: ["heißen", "heißer", "heißes", "heißem"], a: 0, why: "Without an article the adjective shows the case: der Kaffee, Akkusativ → heißen Kaffee." },
{ id: "L21-g3", lesson: 21, skill: "grammar", topic: "Adjective endings without article", type: "mc", q: "Die Kartoffeln brät man mit ___ Knoblauch.", opts: ["frischem", "frischen", "frischer", "frisches"], a: 0, why: "mit takes the Dativ; der Knoblauch without article → frischem (like dem)." },
{ id: "L21-v1", lesson: 21, skill: "vocab", topic: "Cooking verbs", type: "mc", q: "Ich ___ den Kuchen eine Stunde im Ofen.", opts: ["backe", "schäle", "mische", "rühre"], a: 0, why: "A cake is baked in the oven: backen." },
{ id: "L21-w1", lesson: 21, skill: "writing", topic: "Adjective endings without article", type: "gap", q: "Ich esse gern Salat mit ___ Tomaten und ___ Käse. (rot, frisch)", a: ["roten", "frischem"], why: "mit + Dativ without article: plural → roten, der Käse → frischem." },
{ id: "L21-w2", lesson: 21, skill: "writing", topic: "Sequence words + verb second", type: "tr", en: "First I wash the vegetables, then I cut them.", hint: "start with zuerst", de: "Zuerst wasche ich das Gemüse, dann schneide ich es.", alt: ["Zuerst wasche ich das Gemüse und dann schneide ich es.", "Zuerst wasche ich das Gemüse, und dann schneide ich es.", "Zuerst wasche ich das Gemüse, danach schneide ich es.", "Zuerst wasche ich das Gemüse. Dann schneide ich es.", "Zuerst wasche ich das Gemüse und schneide es dann.", "Zuerst wasche ich das Gemüse und danach schneide ich es."], why: "After zuerst and dann the verb comes straight next, then the subject." },

// ---------- Lesson 22: Ämter und Bank ----------
{ id: "L22-g1", lesson: 22, skill: "grammar", topic: "nicht dürfen vs. nicht müssen", type: "mc", q: "Im Bürgeramt ist Telefonieren verboten. Hier ___ man nicht telefonieren.", opts: ["darf", "muss", "braucht"], a: 0, why: "Forbidden (must not) = nicht dürfen; nicht müssen only means 'not necessary'." },
{ id: "L22-g2", lesson: 22, skill: "grammar", topic: "nicht brauchen zu", type: "mc", q: "Sie ___ keinen Termin zu vereinbaren, Sie können einfach kommen.", opts: ["brauchen", "müssen", "dürfen", "sollen"], a: 0, why: "Only brauchen takes zu + infinitive: nicht/kein … brauchen zu = don't need to." },
{ id: "L22-g3", lesson: 22, skill: "grammar", topic: "da- and wo- compounds", type: "mc", q: "Hast du die Bescheinigung schon? – Nein, ich warte noch ___.", opts: ["darauf", "auf es", "worauf", "dafür"], a: 0, why: "To refer back to a thing after warten auf, use da + preposition: darauf." },
{ id: "L22-v1", lesson: 22, skill: "vocab", topic: "Bank vocabulary", type: "mc", q: "Ich möchte 50 Euro abheben. Gibt es hier in der Nähe einen ___?", opts: ["Geldautomaten", "Ausweis", "Vertrag", "Antrag"], a: 0, why: "You withdraw money (abheben) at a cash machine: der Geldautomat." },
{ id: "L22-w1", lesson: 22, skill: "writing", topic: "da- and wo- compounds", type: "gap", q: "___ wartest du? – Auf die neue Bankkarte. (wo + auf)", a: ["Worauf"], why: "To ask about a thing: wo + preposition, with r before a vowel: worauf." },
{ id: "L22-w2", lesson: 22, skill: "writing", topic: "nicht dürfen vs. nicht müssen", type: "tr", en: "You don't have to sign the form.", hint: "formal you", de: "Sie müssen das Formular nicht unterschreiben.", alt: ["Sie brauchen das Formular nicht zu unterschreiben.", "Das Formular müssen Sie nicht unterschreiben.", "Das Formular brauchen Sie nicht zu unterschreiben."], why: "\"don't have to\" = nicht müssen or nicht brauchen zu, never nicht dürfen." },

// ---------- Lesson 23: Natur und Umwelt ----------
{ id: "L23-g1", lesson: 23, skill: "grammar", topic: "Futur I with werden", type: "mc", q: "Im Nationalpark ___ ihr bestimmt viele Vögel sehen.", opts: ["werdet", "wird", "werden", "wirst"], a: 0, why: "Futur I = werden + infinitive; the ihr form is werdet." },
{ id: "L23-g2", lesson: 23, skill: "grammar", topic: "deshalb / trotzdem / sonst", type: "mc", q: "Mach bitte das Licht aus, ___ verbrauchen wir zu viel Strom.", opts: ["sonst", "deshalb", "trotzdem", "weil"], a: 0, why: "sonst = otherwise (a warning); weil would send the verb to the end." },
{ id: "L23-g3", lesson: 23, skill: "grammar", topic: "deshalb / trotzdem / sonst", type: "mc", q: "Das Wasser ist sehr kalt, trotzdem ___ im Fluss.", opts: ["schwimmen die Kinder", "die Kinder schwimmen", "schwimmen", "die Kinder schwimmt"], a: 0, why: "trotzdem takes position 1, so the verb comes next and the subject follows." },
{ id: "L23-v1", lesson: 23, skill: "vocab", topic: "Environment vocabulary", type: "mc", q: "Papier kommt in die blaue Tonne, Plastik in die gelbe: Wir ___ den Müll.", opts: ["trennen", "sparen", "schützen", "verbrauchen"], a: 0, why: "Putting rubbish into different bins = den Müll trennen." },
{ id: "L23-w1", lesson: 23, skill: "writing", topic: "Futur I with werden", type: "gap", q: "Ich ___ in Zukunft weniger Strom ___. (verbrauchen, Futur I)", a: ["werde", "verbrauchen"], why: "Futur I: werden in position 2, the infinitive at the end." },
{ id: "L23-w2", lesson: 23, skill: "writing", topic: "deshalb / trotzdem / sonst", type: "tr", en: "It's raining, but we're going to the forest anyway.", hint: "use trotzdem", de: "Es regnet, trotzdem gehen wir in den Wald.", alt: ["Es regnet, aber wir gehen trotzdem in den Wald.", "Es regnet, aber trotzdem gehen wir in den Wald.", "Es regnet. Trotzdem gehen wir in den Wald.", "Es regnet, trotzdem fahren wir in den Wald.", "Es regnet, aber wir fahren trotzdem in den Wald."], why: "trotzdem in position 1 is followed directly by the verb." },

// ---------- Lesson 24: Freunde und Gefühle ----------
{ id: "L24-g1", lesson: 24, skill: "grammar", topic: "Wishes with Konjunktiv II", type: "mc", q: "Es ist so heiß im Büro. Ich ___ jetzt so gern am Meer!", opts: ["wäre", "hätte", "würde", "war"], a: 0, why: "Konjunktiv II of sein: ich wäre gern … = I'd love to be …" },
{ id: "L24-g2", lesson: 24, skill: "grammar", topic: "Polite requests (Konjunktiv II)", type: "mc", q: "___ Sie mir bitte das Formular erklären?", opts: ["Könnten", "Hätten", "Wären", "Könntest"], a: 0, why: "Polite request: könnten + infinitive; Sie needs the form könnten." },
{ id: "L24-g3", lesson: 24, skill: "grammar", topic: "sich freuen auf / über", type: "mc", q: "Meine Schwester kommt nächste Woche. Ich freue mich schon sehr ___ ihren Besuch.", opts: ["auf", "über", "für", "an"], a: 0, why: "For something in the future: sich freuen auf; über is for something already here." },
{ id: "L24-v1", lesson: 24, skill: "vocab", topic: "Feelings vocabulary", type: "mc", q: "Seit dem Umzug kenne ich hier niemanden. Ich fühle mich oft ___.", opts: ["einsam", "stolz", "zufrieden", "überrascht"], a: 0, why: "Knowing nobody makes you feel lonely: einsam." },
{ id: "L24-w1", lesson: 24, skill: "writing", topic: "sich ärgern über (Perfekt)", type: "gap", q: "Wir ___ uns gestern über den Lärm ___. (sich ärgern, Perfekt)", a: ["haben", "geärgert"], why: "Reflexive verbs form the Perfekt with haben: wir haben uns geärgert." },
{ id: "L24-w2", lesson: 24, skill: "writing", topic: "Polite requests (Konjunktiv II)", type: "tr", en: "Could you help me tomorrow?", de: "Könntest du mir morgen helfen?", alt: ["Könnten Sie mir morgen helfen?", "Könntet ihr mir morgen helfen?", "Könntest du mir morgen bitte helfen?", "Könnten Sie mir morgen bitte helfen?", "Würdest du mir morgen helfen?", "Würden Sie mir morgen helfen?", "Würdet ihr mir morgen helfen?"], why: "Could you … ? = Könntest du / Könnten Sie + infinitive at the end; helfen takes the Dativ (mir)." },

// ---------- Reading ----------
{ id: "L19-r1", lesson: 19, skill: "reading", topic: "Reading: thank-you message", type: "mc", text: "Liebe Anna, vielen Dank für die tolle Feier am Samstag! Die Stimmung war wunderbar, und deine selbst gemachte Torte war die beste. Mein Mann hat dir ja schon einen Gutschein für das Kino gegeben – hoffentlich gefällt er dir. Ich habe dir auch noch etwas gekauft, aber ich habe es leider zu Hause vergessen. Ich gebe es dir nächste Woche persönlich: Es ist ein Buch über Berlin. Liebe Grüße, Miriam", q: "What will Miriam give Anna next week?", opts: ["A book about Berlin", "A cinema voucher", "A homemade cake"], a: 0 },
{ id: "L21-r1", lesson: 21, skill: "reading", topic: "Reading: restaurant review", type: "mc", text: "Gestern waren wir im Restaurant „Am Markt“. Als Vorspeise haben wir Suppe bestellt – leider war sie kalt. Ich habe mich beim Kellner beschwert, und er hat uns sofort heiße Suppe gebracht. Das Hauptgericht war super: frischer Fisch mit Kartoffeln. Nur die Soße war mir ein bisschen zu salzig. Zum Schluss haben wir eine Nachspeise gratis bekommen, weil die Suppe kalt war. Wir haben dem Kellner gern Trinkgeld gegeben.", q: "Why did they get a free dessert?", opts: ["Because the soup was cold", "Because the sauce was too salty", "Because they gave the waiter a big tip"], a: 0 },
{ id: "L22-r1", lesson: 22, skill: "reading", topic: "Reading: office information", type: "mc", text: "Bürgeramt Mitte. Öffnungszeiten: Montag bis Freitag 8 bis 13 Uhr, Donnerstag auch 15 bis 18 Uhr. Sie möchten sich nach einem Umzug anmelden? Dafür brauchen Sie einen Termin. Bitte vereinbaren Sie ihn online. Für einen neuen Ausweis brauchen Sie keinen Termin, ziehen Sie einfach eine Wartenummer. Bringen Sie Ihren alten Ausweis und ein Foto mit. Das Formular müssen Sie nicht mitbringen, Sie bekommen es am Schalter.", q: "Someone has just moved and wants to register. What must they do?", opts: ["Make an appointment online", "Just come and take a queue number", "Bring the form filled in from home", "Come on Saturday morning"], a: 0 },
{ id: "L24-r1", lesson: 24, skill: "reading", topic: "Reading: forum post about friendship", type: "mc", text: "Hallo zusammen! Ich wohne seit einem Jahr in Hamburg und fühle mich oft einsam. Bei der Arbeit sind alle sehr nett, aber ich habe hier noch keine richtigen Freunde. Am Wochenende vermisse ich meine Freunde in Haifa. Ich würde gern neue Leute kennenlernen, vielleicht beim Sport oder in einem Kurs. Ich singe sehr gern, deshalb wäre ein Chor auch toll. Hätte jemand eine Idee? Ich freue mich über jede Antwort! Noa", q: "How does Noa feel in Hamburg?", opts: ["Often lonely", "Happy with many good friends", "Annoyed with her unfriendly colleagues"], a: 0 },

// ---------- Listening ----------
{ id: "L20-l1", lesson: 20, skill: "listening", topic: "Listening: technical problem", type: "mc", audio: "Ich habe mein Passwort vergessen und kann mich nicht einloggen.", q: "What is the speaker's problem?", opts: ["They forgot their password and can't log in", "Their battery is empty", "The Wi-Fi is very slow", "They can't download an app"], a: 0 },
{ id: "L22-l1", lesson: 22, skill: "listening", topic: "Listening: at the office", type: "mc", audio: "Sie brauchen nicht zu warten, Sie sind sofort dran.", q: "What is the person told?", opts: ["They don't have to wait – it's their turn now", "They must wait a long time", "They must take a queue number", "They need an appointment"], a: 0 },
{ id: "L23-l1", lesson: 23, skill: "listening", topic: "Listening: environment advice", type: "mc", audio: "Nimm eine Tasche mit, sonst musst du eine Plastiktüte kaufen.", q: "Why should the listener take a bag?", opts: ["Otherwise they'll have to buy a plastic bag", "Because it will rain", "Because the shop has no bags at all", "To separate the rubbish"], a: 0 },
{ id: "L21-l1", lesson: 21, skill: "listening", topic: "Adjective endings without article", type: "dict", audio: "Zum Frühstück esse ich gern frisches Brot mit Käse.", q: "Zum Frühstück esse ich gern ___ Brot mit Käse.", a: ["frisches"] },
{ id: "L24-l1", lesson: 24, skill: "listening", topic: "sich freuen über", type: "dict", audio: "Ich habe mich sehr über deine Nachricht gefreut.", q: "Ich habe mich sehr über deine Nachricht ___.", a: ["gefreut"] }
);
