// Level exam items, lessons 25-30, written for this app.
EXAM.push(
// ---------- Lesson 25: Stadt oder Land ----------
{ id: "L25-g1", lesson: 25, skill: "grammar", topic: "Relative pronouns: Akkusativ", type: "mc", q: "Der Bäcker, ___ ich jeden Morgen sehe, ist sehr freundlich.", opts: ["den", "der", "dem", "denen"], a: 0, why: "The baker is the object of 'sehe' inside the relative clause, so masculine accusative: den." },
{ id: "L25-g2", lesson: 25, skill: "grammar", topic: "Relative pronouns with prepositions", type: "mc", q: "Die Kollegen, mit ___ ich jeden Tag pendle, wohnen alle im Vorort.", opts: ["denen", "die", "den", "der"], a: 0, why: "mit takes the dative; the dative plural relative pronoun is denen." },
{ id: "L25-g3", lesson: 25, skill: "grammar", topic: "Pros and cons: dafür + word order", type: "mc", q: "Die Wohnung ist ziemlich klein, dafür ___ einen großen Balkon.", opts: ["hat sie", "sie hat", "hat", "sie"], a: 0, why: "After dafür the verb comes next (position 2), then the subject: dafür hat sie." },
{ id: "L25-v1", lesson: 25, skill: "vocab", topic: "City and countryside vocabulary", type: "mc", q: "Um acht Uhr ist die S-Bahn immer so ___, dass man keinen Sitzplatz findet.", opts: ["überfüllt", "abgelegen", "ländlich", "anonym"], a: 0, why: "überfüllt = overcrowded." },
{ id: "L25-w1", lesson: 25, skill: "writing", topic: "Relative pronouns: Dativ", type: "gap", q: "Der Mann, ___ das Grundstück gehört, wohnt in der Großstadt. (relative pronoun)", a: ["dem/welchem"], why: "gehören takes the dative: dem Mann gehört das Grundstück → der Mann, dem …" },
{ id: "L25-w2", lesson: 25, skill: "writing", topic: "Relative clauses with prepositions", type: "tr", en: "I like the area in which my sister lives.", hint: "use a relative clause", de: "Mir gefällt die Gegend, in der meine Schwester wohnt.", alt: ["Mir gefällt die Gegend, in der meine Schwester lebt.", "Ich mag die Gegend, in der meine Schwester wohnt.", "Ich mag die Gegend, in der meine Schwester lebt.", "Die Gegend, in der meine Schwester wohnt, gefällt mir.", "Die Gegend, in der meine Schwester lebt, gefällt mir.", "Die Gegend, in der meine Schwester wohnt, mag ich.", "Die Gegend, in der meine Schwester lebt, mag ich.", "Mir gefällt die Gegend, wo meine Schwester wohnt.", "Ich mag die Gegend, wo meine Schwester wohnt.", "Mir gefällt die Gegend, wo meine Schwester lebt.", "Ich mag die Gegend, wo meine Schwester lebt.", "Die Gegend, wo meine Schwester wohnt, gefällt mir.", "Die Gegend, wo meine Schwester lebt, gefällt mir."], why: "die Gegend is feminine; in + where? takes the dative: in der." },

// ---------- Lesson 26: Bewerbung und Beruf ----------
{ id: "L26-g1", lesson: 26, skill: "grammar", topic: "zu + infinitive with separable verbs", type: "mc", q: "Ich habe vergessen, meinen Chef ___.", opts: ["anzurufen", "zu anrufen", "anrufen", "angerufen"], a: 0, why: "After vergessen use zu + infinitive; with separable verbs zu goes between prefix and verb: anzurufen." },
{ id: "L26-g2", lesson: 26, skill: "grammar", topic: "No zu after modal verbs", type: "mc", q: "Leider kann ich morgen nicht zum Vorstellungsgespräch ___.", opts: ["kommen", "zu kommen", "gekommen", "kommt"], a: 0, why: "Modal verbs like können take a plain infinitive without zu." },
{ id: "L26-g3", lesson: 26, skill: "grammar", topic: "damit vs. um … zu", type: "mc", q: "Die Chefin erklärt alles genau, ___ die neue Kollegin keine Fehler macht.", opts: ["damit", "um", "zu", "denn"], a: 0, why: "Different subjects (die Chefin / die Kollegin) and a conjugated verb at the end → damit." },
{ id: "L26-v1", lesson: 26, skill: "vocab", topic: "Job and application vocabulary", type: "mc", q: "Der Vertrag ist ___: Er endet nach zwölf Monaten.", opts: ["befristet", "belastbar", "teamfähig", "motiviert"], a: 0, why: "befristet = fixed-term, limited in time." },
{ id: "L26-w1", lesson: 26, skill: "writing", topic: "zu + infinitive with separable verbs", type: "gap", q: "Hast du Lust, heute Abend mit uns ___? (ausgehen)", a: ["auszugehen"], why: "Lust haben + zu-infinitive; zu goes between the prefix and the verb: auszugehen." },
{ id: "L26-w2", lesson: 26, skill: "writing", topic: "Purpose with um … zu", type: "tr", en: "I'm calling the company to ask about the salary.", hint: "use um … zu", de: "Ich rufe die Firma an, um nach dem Gehalt zu fragen.", alt: ["Ich rufe bei der Firma an, um nach dem Gehalt zu fragen.", "Ich rufe die Firma an, um wegen des Gehalts zu fragen.", "Ich rufe bei der Firma an, um wegen des Gehalts zu fragen.", "Ich rufe die Firma an, um mich nach dem Gehalt zu erkundigen.", "Ich rufe bei der Firma an, um mich nach dem Gehalt zu erkundigen."], why: "Same subject in both parts → um … zu, with the infinitive at the end." },

// ---------- Lesson 27: Erinnerungen ----------
{ id: "L27-g1", lesson: 27, skill: "grammar", topic: "Präteritum of irregular verbs", type: "mc", q: "Als Kind ___ ich jeden Sommer mit meinen Eltern ans Meer.", opts: ["fuhr", "fahrte", "fuhrte", "fährte"], a: 0, why: "fahren is irregular: the stem changes to fuhr and there is no -te." },
{ id: "L27-g2", lesson: 27, skill: "grammar", topic: "als vs. wenn", type: "mc", q: "Immer ___ wir Ferien hatten, besuchten wir unsere Cousins in Tel Aviv.", opts: ["wenn", "als", "wann", "ob"], a: 0, why: "Repeated events in the past (immer …) take wenn; als is for one single event or period." },
{ id: "L27-g3", lesson: 27, skill: "grammar", topic: "Plusquamperfekt with nachdem", type: "mc", q: "Nachdem sie nach Hamburg gezogen ___, fühlte sie sich zuerst sehr allein.", opts: ["war", "hatte", "ist", "wurde"], a: 0, why: "After nachdem use the Plusquamperfekt; ziehen (movement) takes sein → war gezogen." },
{ id: "L27-v1", lesson: 27, skill: "vocab", topic: "Describing yourself as a child", type: "mc", q: "Als Kind war ich sehr ___: Ich wollte immer alles wissen.", opts: ["neugierig", "schüchtern", "frech", "verwöhnt"], a: 0, why: "neugierig = curious." },
{ id: "L27-w1", lesson: 27, skill: "writing", topic: "Präteritum of irregular verbs", type: "gap", q: "Früher ___ mir mein Bruder jeden Abend eine Geschichte vor. (vorlesen, Präteritum)", a: ["las"], why: "lesen is irregular: Präteritum las; the prefix vor goes to the end." },
{ id: "L27-w2", lesson: 27, skill: "writing", topic: "als for a period in the past", type: "tr", en: "When I was twelve, I often played pranks on my sister.", hint: "use als", de: "Als ich zwölf war, spielte ich meiner Schwester oft Streiche.", alt: ["Als ich zwölf Jahre alt war, spielte ich meiner Schwester oft Streiche.", "Als ich zwölf war, habe ich meiner Schwester oft Streiche gespielt.", "Als ich zwölf Jahre alt war, habe ich meiner Schwester oft Streiche gespielt.", "Als ich zwölf war, spielte ich oft meiner Schwester Streiche.", "Als ich zwölf war, habe ich oft meiner Schwester Streiche gespielt.", "Als ich zwölf Jahre alt war, spielte ich oft meiner Schwester Streiche.", "Als ich zwölf Jahre alt war, habe ich oft meiner Schwester Streiche gespielt."], why: "One period in the past → als; the verb goes to the end of the als-clause, then the main clause starts with the verb." },

// ---------- Lesson 28: Beim Arzt und im Krankenhaus ----------
{ id: "L28-g1", lesson: 28, skill: "grammar", topic: "Passive present tense", type: "mc", q: "In der Notaufnahme ___ die Patienten sofort untersucht.", opts: ["werden", "wird", "wurde", "haben"], a: 0, why: "Passive = werden + Partizip II; the subject die Patienten is plural → werden." },
{ id: "L28-g2", lesson: 28, skill: "grammar", topic: "Passive Präteritum", type: "mc", q: "Letzte Woche ___ meine Schwester am Fuß operiert.", opts: ["wurde", "wurden", "wird", "ist"], a: 0, why: "Past passive = wurde + Partizip II; the subject (meine Schwester) is singular." },
{ id: "L28-g3", lesson: 28, skill: "grammar", topic: "Passive with von + Dativ", type: "mc", q: "Die Kinder wurden ___ Kinderarzt geimpft.", opts: ["vom", "von den", "mit dem", "von der"], a: 0, why: "The person doing the action is named with von + Dativ: von dem (vom) Kinderarzt." },
{ id: "L28-v1", lesson: 28, skill: "vocab", topic: "Symptoms", type: "mc", q: "Mir ist ___, ich glaube, ich muss mich kurz setzen.", opts: ["schwindlig", "versichert", "allergisch", "gesetzlich"], a: 0, why: "Mir ist schwindlig = I feel dizzy." },
{ id: "L28-w1", lesson: 28, skill: "writing", topic: "Passive Präteritum", type: "gap", q: "Gestern ___ mir vom Hausarzt ein neues Medikament ___. (verschreiben)", a: ["wurde", "verschrieben"], why: "Past passive: wurde + Partizip II (verschrieben) at the end." },
{ id: "L28-w2", lesson: 28, skill: "writing", topic: "Passive with von + Dativ", type: "tr", en: "Yesterday I was examined by a specialist.", hint: "passive, Präteritum", de: "Gestern wurde ich von einem Facharzt untersucht.", alt: ["Ich wurde gestern von einem Facharzt untersucht.", "Gestern wurde ich von einer Fachärztin untersucht.", "Ich wurde gestern von einer Fachärztin untersucht.", "Gestern bin ich von einem Facharzt untersucht worden.", "Ich bin gestern von einem Facharzt untersucht worden.", "Gestern bin ich von einer Fachärztin untersucht worden.", "Ich bin gestern von einer Fachärztin untersucht worden.", "Gestern wurde ich von einem Spezialisten untersucht.", "Ich wurde gestern von einem Spezialisten untersucht."], why: "'I was examined' = ich wurde untersucht; 'by' = von + Dativ." },

// ---------- Lesson 29: Pannen auf Reisen ----------
{ id: "L29-g1", lesson: 29, skill: "grammar", topic: "Konjunktiv II past with wäre", type: "mc", q: "Ohne den Stau ___ wir pünktlich am Flughafen angekommen.", opts: ["wären", "hätten", "würden", "haben"], a: 0, why: "Unreal past = hätte/wäre + Partizip II; ankommen takes sein → wären angekommen." },
{ id: "L29-g2", lesson: 29, skill: "grammar", topic: "Unreal conditions in the past", type: "mc", q: "Wenn ich den Wecker gehört ___, hätte ich den Zug nicht verpasst.", opts: ["hätte", "wäre", "habe", "würde"], a: 0, why: "Both parts use Konjunktiv II past; hören takes haben → gehört hätte." },
{ id: "L29-g3", lesson: 29, skill: "grammar", topic: "Regret: hätte … sollen", type: "mc", q: "Du hättest im Restaurant vorher einen Tisch ___ sollen.", opts: ["reservieren", "reserviert", "zu reservieren", "reservierst"], a: 0, why: "'should have done' = hätte + infinitive + sollen (two infinitives at the end)." },
{ id: "L29-v1", lesson: 29, skill: "vocab", topic: "Travel problems vocabulary", type: "mc", q: "Der Zug hatte Verspätung, deshalb habe ich meinen ___ nach Köln verpasst.", opts: ["Anschluss", "Bahnsteig", "Schaden", "Durchsage"], a: 0, why: "der Anschluss = connecting train or flight." },
{ id: "L29-w1", lesson: 29, skill: "writing", topic: "Unreal conditions in the past", type: "gap", q: "Wenn wir mehr Geld ___ ___, hätten wir einen Mietwagen genommen. (haben)", a: ["gehabt", "hätten"], why: "Unreal past condition: Partizip II + hätte at the end of the wenn-clause." },
{ id: "L29-w2", lesson: 29, skill: "writing", topic: "Unreal conditions in the past", type: "tr", en: "If we had booked earlier, the hotel would have been cheaper.", de: "Wenn wir früher gebucht hätten, wäre das Hotel billiger gewesen.", alt: ["Wenn wir früher gebucht hätten, wäre das Hotel günstiger gewesen.", "Hätten wir früher gebucht, wäre das Hotel billiger gewesen.", "Hätten wir früher gebucht, wäre das Hotel günstiger gewesen.", "Wenn wir eher gebucht hätten, wäre das Hotel billiger gewesen.", "Wenn wir eher gebucht hätten, wäre das Hotel günstiger gewesen.", "Das Hotel wäre billiger gewesen, wenn wir früher gebucht hätten.", "Das Hotel wäre günstiger gewesen, wenn wir früher gebucht hätten.", "Hätten wir eher gebucht, wäre das Hotel billiger gewesen.", "Hätten wir eher gebucht, wäre das Hotel günstiger gewesen.", "Das Hotel wäre billiger gewesen, wenn wir eher gebucht hätten.", "Das Hotel wäre günstiger gewesen, wenn wir eher gebucht hätten."], why: "Two unreal past parts: gebucht hätten … wäre … gewesen." },

// ---------- Lesson 30: Nachrichten und Medien ----------
{ id: "L30-g1", lesson: 30, skill: "grammar", topic: "Genitive articles", type: "mc", q: "Der Titel ___ Artikels ist leider viel zu lang.", opts: ["des", "dem", "der", "den"], a: 0, why: "der Artikel is masculine; genitive = des Artikels (noun + -s)." },
{ id: "L30-g2", lesson: 30, skill: "grammar", topic: "wegen + Genitiv", type: "mc", q: "Wegen ___ Unfalls gab es auf der Autobahn einen langen Stau.", opts: ["des", "dem", "den", "der"], a: 0, why: "wegen takes the genitive; masculine: des Unfalls." },
{ id: "L30-g3", lesson: 30, skill: "grammar", topic: "Genitive prepositions: statt, trotz, wegen, während", type: "mc", q: "___ eines Fernsehers hat sie nur einen alten Laptop.", opts: ["Statt", "Wegen", "Trotz", "Während"], a: 0, why: "statt = instead of (+ Genitiv): she has a laptop instead of a TV." },
{ id: "L30-v1", lesson: 30, skill: "vocab", topic: "Media vocabulary", type: "mc", q: "Die Zeitung hat den Bericht gestern auf ihrer Webseite ___.", opts: ["veröffentlicht", "abonniert", "informiert", "berichtet"], a: 0, why: "veröffentlichen = to publish." },
{ id: "L30-w1", lesson: 30, skill: "writing", topic: "Genitive with -n nouns", type: "gap", q: "Der Beitrag ___ ___ wurde tausendmal geteilt. (unser Kollege)", a: ["unseres", "Kollegen"], why: "Genitive masculine: unseres; der Kollege is an -n noun → des Kollegen." },
{ id: "L30-w2", lesson: 30, skill: "writing", topic: "trotz + Genitiv", type: "tr", en: "Despite the criticism, the government is planning a new law.", de: "Trotz der Kritik plant die Regierung ein neues Gesetz.", alt: ["Die Regierung plant trotz der Kritik ein neues Gesetz."], why: "trotz + Genitiv (der Kritik); after the trotz-phrase the verb comes next." },

// ---------- Reading ----------
{ id: "L26-r1", lesson: 26, skill: "reading", topic: "Reading a job ad", type: "mc",
  text: "Wir suchen ab 1. März eine Bürokauffrau oder einen Bürokaufmann in Teilzeit (20 Stunden pro Woche). Ihre Aufgaben: Sie beantworten Anfragen von Kunden, planen Termine und arbeiten eng mit unserer Personalabteilung zusammen. Voraussetzung ist eine abgeschlossene Ausbildung. Berufserfahrung ist von Vorteil, aber kein Muss. Gute Englischkenntnisse sind wichtig, weil viele unserer Kunden aus dem Ausland kommen. Sie sind zuverlässig, teamfähig und belastbar? Dann freuen wir uns auf Ihre Bewerbung! Der Vertrag ist zunächst auf ein Jahr befristet, die Probezeit dauert sechs Monate. Bitte schicken Sie Ihr Anschreiben und Ihren Lebenslauf bis zum 31. Januar per E-Mail an Frau Keller.",
  q: "Which statement about the job is true?", opts: ["It is part-time and the contract is limited to one year.", "Work experience is a requirement.", "It is a full-time, permanent position.", "Applications must be sent by post."], a: 0 },
{ id: "L27-r1", lesson: 27, skill: "reading", topic: "Reading a childhood story", type: "mc",
  text: "Wenn ich an meine Kindheit zurückdenke, sehe ich zuerst den Garten meiner Großeltern. Jeden Sommer verbrachten mein Bruder und ich sechs Wochen bei ihnen auf dem Land. Wir kletterten auf Bäume, bauten Hütten und kamen erst nach Hause, wenn es dunkel wurde. Meine Oma verwöhnte uns mit Kuchen, und mein Opa erzählte Geschichten aus seiner Jugend. Einmal, als ich neun war, wollten wir heimlich im Wald schlafen. Nachdem wir eine Stunde im Zelt gelegen hatten, hörten wir plötzlich ein lautes Geräusch. Wir rannten sofort zurück ins Haus! Am nächsten Morgen erfuhren wir, dass es nur die Katze der Nachbarn gewesen war. Heute lachen wir oft über dieses Abenteuer.",
  q: "What happened on the night in the forest?", opts: ["The two children heard a noise and ran back to the house.", "The children slept in the tent until the next morning.", "Their grandfather came to the forest and took them home.", "A neighbour's dog attacked their tent."], a: 0 },
{ id: "L29-r1", lesson: 29, skill: "reading", topic: "Reading a complaint email", type: "mc",
  text: "Sehr geehrte Damen und Herren, vom 3. bis 10. August habe ich in Ihrem Hotel ein Doppelzimmer mit Meerblick gebucht. Leider war ich mit meinem Aufenthalt gar nicht zufrieden. Schon am ersten Abend funktionierte die Klimaanlage nicht, und wir konnten wegen der Hitze kaum schlafen. Ich habe mich sofort an der Rezeption beschwert, aber niemand kam, um sie zu reparieren. Außerdem hatte das Zimmer keinen Meerblick, sondern einen Blick auf den Parkplatz. Hätte ich das gewusst, hätte ich ein anderes Hotel gebucht. Ich hätte erwartet, dass man uns wenigstens ein anderes Zimmer anbietet. Deshalb bitte ich Sie, mir einen Teil des Preises zu erstatten. Mit freundlichen Grüßen, Daniel Weber",
  q: "Why is Daniel complaining?", opts: ["The air conditioning didn't work and the room looked onto the car park.", "The room was too cold and the reception was always closed.", "The hotel cancelled his reservation at the last minute.", "The air conditioning was noisy, although it was repaired quickly."], a: 0 },
{ id: "L30-r1", lesson: 30, skill: "reading", topic: "Reading a short news article", type: "mc",
  text: "Wie informieren sich junge Menschen heute? Eine neue Studie, die letzte Woche veröffentlicht wurde, zeigt: Nur zwölf Prozent der 18- bis 25-Jährigen lesen regelmäßig eine gedruckte Zeitung. Statt einer Zeitung nutzen die meisten soziale Medien oder Apps. Das Problem: Wegen der vielen Falschmeldungen wissen viele nicht, welchen Quellen sie glauben können. Trotzdem prüfen nur wenige junge Leute, woher eine Nachricht kommt. Die Autoren der Studie wünschen sich deshalb, dass Schulen mehr über Medien unterrichten. Während des Unterrichts sollen Schüler lernen, glaubwürdige Berichte von Falschmeldungen zu unterscheiden. Viele Lehrer finden die Idee gut, sagen aber, dass ihnen dafür die Zeit fehlt.",
  q: "According to the text, which statement is true?", opts: ["Most young people get their news from social media or apps rather than printed newspapers.", "Most young people regularly read a printed newspaper.", "Most young people check where a news story comes from.", "Teachers say they have plenty of time for media lessons."], a: 0 },

// ---------- Listening ----------
{ id: "L25-l1", lesson: 25, skill: "listening", topic: "Listening: where to live", type: "mc", audio: "Ich würde gern in einem Vorort leben, in dem es viel Natur gibt.", q: "Where would the speaker like to live?", opts: ["In a suburb with a lot of nature", "In the city centre near the theatres", "On a remote farm far from any town", "In a high-rise right by the sea"], a: 0 },
{ id: "L28-l1", lesson: 28, skill: "listening", topic: "Listening: health insurance", type: "mc", audio: "In Israel ist jeder bei einer Krankenkasse versichert, und viele Kosten werden vom Staat übernommen.", q: "What does the speaker say about Israel?", opts: ["Everyone is insured with a health fund, and the state covers many costs.", "Only people with a job are insured.", "Patients have to pay all costs themselves.", "Most people have private insurance through their employer."], a: 0 },
{ id: "L30-l1", lesson: 30, skill: "listening", topic: "Listening: opinions on media", type: "mc", audio: "Meiner Meinung nach sind soziale Medien praktisch, aber man muss immer die Quelle prüfen.", q: "What is the speaker's opinion of social media?", opts: ["Practical, but you always have to check the source", "Dangerous, so it's better not to use them", "Always reliable, so there's no need to check anything", "Boring, because of all the advertising"], a: 0 },
{ id: "L27-l1", lesson: 27, skill: "listening", topic: "Plusquamperfekt with nachdem", type: "dict", audio: "Nachdem wir umgezogen waren, hatte ich lange Heimweh.", q: "Nachdem wir umgezogen ___, hatte ich lange Heimweh.", a: ["waren"] },
{ id: "L29-l1", lesson: 29, skill: "listening", topic: "Unreal conditions in the past", type: "dict", audio: "Wenn wir früher losgefahren wären, hätten wir den Flug nicht verpasst.", q: "Wenn wir früher losgefahren ___, hätten wir den Flug nicht verpasst.", a: ["wären"] }
);
