// Level exam items, lessons 31-36, written for this app.
EXAM.push(
// ---------- Lesson 31: Geld und Konsum ----------
{ id: "L31-g1", lesson: 31, skill: "grammar", topic: "n-Deklination", type: "mc", q: "Die Bankangestellte hat dem ___ die Kontoauszüge erklärt.", opts: ["Kunden", "Kunde", "Kundes", "Kunds"], a: 0, why: "Kunde is an n-noun: it adds -n in every case except the nominative singular (dem Kunden)." },
{ id: "L31-g2", lesson: 31, skill: "grammar", topic: "n-Deklination (Herr)", type: "mc", q: "Kannst du bitte ___ Becker von der Bank zurückrufen?", opts: ["Herrn", "Herr", "Herren", "Herrns"], a: 0, why: "Herr is an n-noun: accusative singular is Herrn (Herren is the plural)." },
{ id: "L31-g3", lesson: 31, skill: "grammar", topic: "Adjectives used as nouns", type: "mc", q: "Gestern habe ich mit einem ___ über meine Schulden gesprochen.", opts: ["Bekannten", "Bekannter", "Bekannte", "Bekanntem"], a: 0, why: "Nominalised adjectives keep adjective endings: dative after einem → einem Bekannten." },
{ id: "L31-v1", lesson: 31, skill: "vocab", topic: "Shopping & complaints vocabulary", type: "mc", q: "Der Fernseher war schon nach einer Woche kaputt, deshalb habe ich ihn im Geschäft ___.", opts: ["reklamiert", "geliehen", "gespart", "geleistet"], a: 0, why: "reklamieren = to complain about a faulty product." },
{ id: "L31-w1", lesson: 31, skill: "writing", topic: "n-Deklination", type: "gap", q: "Ich habe gestern mit unserem ___ über die hohe Miete gesprochen. (Nachbar)", a: ["Nachbarn"], why: "Nachbar is an n-noun: dative mit unserem Nachbarn." },
{ id: "L31-w2", lesson: 31, skill: "writing", topic: "sich leisten", type: "tr", en: "We can't afford a holiday this year.", de: "Dieses Jahr können wir uns keinen Urlaub leisten.", alt: ["Wir können uns dieses Jahr keinen Urlaub leisten.", "In diesem Jahr können wir uns keinen Urlaub leisten.", "Wir können uns in diesem Jahr keinen Urlaub leisten.", "Einen Urlaub können wir uns dieses Jahr nicht leisten.", "Einen Urlaub können wir uns in diesem Jahr nicht leisten.", "Dieses Jahr können wir uns keine Ferien leisten.", "Wir können uns dieses Jahr keine Ferien leisten."], why: "sich (Dat.) etwas leisten: wir können uns … leisten; 'no holiday' = keinen Urlaub." },

// ---------- Lesson 32: Beziehungen ----------
{ id: "L32-g1", lesson: 32, skill: "grammar", topic: "sowohl … als auch", type: "mc", q: "Sowohl mein Schwager ___ meine Schwägerin arbeiten im Krankenhaus.", opts: ["als auch", "sondern auch", "noch", "oder"], a: 0, why: "sowohl is always completed by als auch (both … and)." },
{ id: "L32-g2", lesson: 32, skill: "grammar", topic: "nicht nur … sondern auch", type: "mc", q: "Meine Schwiegermutter ist nicht nur sehr nett, ___ auch eine tolle Köchin.", opts: ["sondern", "aber", "als", "oder"], a: 0, why: "nicht nur is completed by sondern auch (not only … but also)." },
{ id: "L32-g3", lesson: 32, skill: "grammar", topic: "entweder … oder", type: "mc", q: "Am Wochenende besuchen wir ___ meine Eltern oder deine Schwester.", opts: ["entweder", "weder", "sowohl", "nicht nur"], a: 0, why: "Two alternatives with oder: entweder … oder (either … or)." },
{ id: "L32-v1", lesson: 32, skill: "vocab", topic: "Relationship vocabulary", type: "mc", q: "Wenn man dem Partner nicht glauben kann, fehlt in der Ehe etwas sehr Wichtiges, nämlich ___.", opts: ["Vertrauen", "Eifersucht", "Scheidung", "Erziehung"], a: 0, why: "das Vertrauen = trust." },
{ id: "L32-w1", lesson: 32, skill: "writing", topic: "weder … noch", type: "gap", q: "Wir haben ___ Zeit ___ Geld für einen langen Urlaub. (neither … nor)", a: ["weder", "noch"], why: "weder … noch = neither … nor; it is already negative, so no kein." },
{ id: "L32-w2", lesson: 32, skill: "writing", topic: "sowohl … als auch", type: "tr", en: "I get on well with both my brother-in-law and my sister-in-law.", hint: "use sowohl … als auch", de: "Ich verstehe mich sowohl mit meinem Schwager als auch mit meiner Schwägerin gut.", alt: ["Ich verstehe mich gut sowohl mit meinem Schwager als auch mit meiner Schwägerin.", "Sowohl mit meinem Schwager als auch mit meiner Schwägerin verstehe ich mich gut."], why: "sich gut verstehen mit + dative; sowohl … als auch links the two people." },

// ---------- Lesson 33: Kultur erleben ----------
{ id: "L33-g1", lesson: 33, skill: "grammar", topic: "Relative clauses with prepositions", type: "mc", q: "Das ist die Galerie, in ___ ich meinen ersten Job hatte.", opts: ["der", "die", "dem", "denen"], a: 0, why: "in (where?) takes the dative; die Galerie is feminine → in der." },
{ id: "L33-g2", lesson: 33, skill: "grammar", topic: "Relative clauses with prepositions", type: "mc", q: "Die Schauspieler, mit ___ wir nach der Premiere gesprochen haben, waren sehr nett.", opts: ["denen", "den", "die", "dem"], a: 0, why: "mit takes the dative; the plural dative relative pronoun is denen." },
{ id: "L33-g3", lesson: 33, skill: "grammar", topic: "Relative was", type: "mc", q: "Die Vorstellung hat erst um zehn Uhr abends angefangen, ___ ich ziemlich spät fand.", opts: ["was", "das", "wo", "welches"], a: 0, why: "When the relative clause refers to a whole sentence, use was." },
{ id: "L33-v1", lesson: 33, skill: "vocab", topic: "Culture vocabulary", type: "mc", q: "Wir wollten die Premiere sehen, aber es gab keine Karten mehr: Die Vorstellung war ___.", opts: ["ausverkauft", "enttäuschend", "beeindruckend", "begeistert"], a: 0, why: "ausverkauft = sold out." },
{ id: "L33-w1", lesson: 33, skill: "writing", topic: "Relative clauses with prepositions", type: "gap", q: "Die Oper, auf ___ ich mich so gefreut hatte, war leider enttäuschend. (relative pronoun)", a: ["die/welche"], why: "sich freuen auf + accusative; die Oper is feminine → auf die." },
{ id: "L33-w2", lesson: 33, skill: "writing", topic: "Relative wo after places", type: "tr", en: "Haifa is a city where you can see many exhibitions.", hint: "use wo", de: "Haifa ist eine Stadt, wo man viele Ausstellungen sehen kann.", alt: ["Haifa ist eine Stadt, in der man viele Ausstellungen sehen kann.", "Haifa ist eine Stadt, wo man viele Ausstellungen besuchen kann.", "Haifa ist eine Stadt, in der man viele Ausstellungen besuchen kann.", "Haifa ist eine Stadt, wo man sich viele Ausstellungen ansehen kann.", "Haifa ist eine Stadt, in der man sich viele Ausstellungen ansehen kann.", "Haifa ist eine Stadt, wo man sich viele Ausstellungen anschauen kann.", "Haifa ist eine Stadt, in der man sich viele Ausstellungen anschauen kann."], why: "After a place, wo (= in der) introduces the relative clause; verb at the end." },

// ---------- Lesson 34: Zukunft und Umwelt ----------
{ id: "L34-g1", lesson: 34, skill: "grammar", topic: "Futur I (prediction)", type: "mc", q: "Experten glauben, dass die Temperaturen in Israel weiter steigen ___.", opts: ["werden", "wird", "worden", "sind"], a: 0, why: "Futur I = werden + infinitive; plural subject → werden, at the end of the dass-clause." },
{ id: "L34-g2", lesson: 34, skill: "grammar", topic: "Futur I (assumption)", type: "mc", q: "Der Bus ist noch nicht da. Er ___ wohl wegen des Unwetters Verspätung haben.", opts: ["wird", "ist", "werden", "hat"], a: 0, why: "werden + wohl + infinitive expresses an assumption about now: er wird … haben." },
{ id: "L34-g3", lesson: 34, skill: "grammar", topic: "Passive with modal verbs", type: "mc", q: "Plastikverpackungen sollten stärker ___ werden.", opts: ["reduziert", "reduzieren", "reduzierte", "zu reduzieren"], a: 0, why: "Passive with a modal: modal + Partizip II + werden (reduziert werden)." },
{ id: "L34-v1", lesson: 34, skill: "vocab", topic: "Environment vocabulary", type: "mc", q: "Im Sommer hat es drei Monate nicht geregnet. Die lange ___ war für die Bauern ein großes Problem.", opts: ["Dürre", "Überschwemmung", "Verpackung", "Windkraft"], a: 0, why: "die Dürre = drought (a long time without rain)." },
{ id: "L34-w1", lesson: 34, skill: "writing", topic: "Passive with modal verbs", type: "gap", q: "Ich bin sicher, dass alte Batterien nicht in den Hausmüll ___ ___ dürfen. (werfen)", a: ["geworfen", "werden"], why: "Passive infinitive (Partizip II + werden) before the modal at the end of the dass-clause." },
{ id: "L34-w2", lesson: 34, skill: "writing", topic: "Passive with modal verbs", type: "tr", en: "In our city, old phones must not be thrown away.", hint: "passive with a modal verb", de: "In unserer Stadt dürfen alte Handys nicht weggeworfen werden.", alt: ["Alte Handys dürfen in unserer Stadt nicht weggeworfen werden.", "In unserer Stadt dürfen keine alten Handys weggeworfen werden."], why: "'must not' = dürfen nicht (müssen nicht means 'don't have to'); passive: weggeworfen werden." },

// ---------- Lesson 35: Gesellschaft und Politik ----------
{ id: "L35-g1", lesson: 35, skill: "grammar", topic: "obwohl vs. trotzdem", type: "mc", q: "Er lebt erst seit einem Jahr in Deutschland. ___ spricht er schon sehr gut Deutsch.", opts: ["Trotzdem", "Obwohl", "Weil", "Deshalb"], a: 0, why: "trotzdem is an adverb in a main clause (verb right after it) and expresses a surprising result." },
{ id: "L35-g2", lesson: 35, skill: "grammar", topic: "Time clauses: nachdem", type: "mc", q: "___ sie die deutsche Staatsangehörigkeit bekommen hatte, durfte sie zum ersten Mal wählen.", opts: ["Nachdem", "Nach", "Bevor", "Während"], a: 0, why: "nachdem (conjunction + clause) for the earlier action, with Plusquamperfekt; nach is a preposition." },
{ id: "L35-g3", lesson: 35, skill: "grammar", topic: "je … desto", type: "mc", q: "Je länger sie in Deutschland lebt, ___.", opts: ["desto besser versteht sie die Kultur", "desto besser sie versteht die Kultur", "desto sie versteht die Kultur besser", "desto besser die Kultur sie versteht"], a: 0, why: "desto + comparative, then the verb, then the subject." },
{ id: "L35-v1", lesson: 35, skill: "vocab", topic: "Society & volunteering vocabulary", type: "mc", q: "Meine Mutter arbeitet ___ in einem Verein für Flüchtlinge – sie bekommt kein Geld dafür.", opts: ["ehrenamtlich", "gemeinsam", "sparsam", "geschieden"], a: 0, why: "ehrenamtlich = voluntary, unpaid." },
{ id: "L35-w1", lesson: 35, skill: "writing", topic: "obwohl (verb at the end)", type: "gap", q: "Obwohl es heute stark ___, nehmen Tausende an der Demonstration ___. (regnen / teilnehmen)", a: ["regnet", "teil"], why: "obwohl sends the verb to the end; in the main clause the separable prefix teil goes to the end." },
{ id: "L35-w2", lesson: 35, skill: "writing", topic: "Time clauses: bevor", type: "tr", en: "Before I donate money, I always find out about the aid organisation.", hint: "use bevor and sich informieren", de: "Bevor ich Geld spende, informiere ich mich immer über die Hilfsorganisation.", alt: ["Ich informiere mich immer über die Hilfsorganisation, bevor ich Geld spende."], why: "bevor sends its verb to the end; the main clause then starts with the verb (informiere ich)." },

// ---------- Lesson 36: Arbeitswelt ----------
{ id: "L36-g1", lesson: 36, skill: "grammar", topic: "Participles as adjectives", type: "mc", q: "Wegen der ___ Kosten müssen wir weniger Überstunden machen.", opts: ["steigenden", "steigende", "steigend", "steigender"], a: 0, why: "Partizip I takes normal adjective endings: genitive plural after der → steigenden." },
{ id: "L36-g2", lesson: 36, skill: "grammar", topic: "lassen (Perfekt)", type: "mc", q: "Wir haben den Vertrag von einem Kollegen übersetzen ___.", opts: ["lassen", "gelassen", "gelässt", "lässt"], a: 0, why: "With a second infinitive, the Perfekt of lassen is the infinitive: prüfen lassen, not gelassen." },
{ id: "L36-g3", lesson: 36, skill: "grammar", topic: "Reacting to opinions (widersprechen + Dat.)", type: "mc", q: "In diesem Punkt muss ich ___ Chefin widersprechen.", opts: ["meiner", "meine", "meinem", "mein"], a: 0, why: "widersprechen (like zustimmen) takes the dative: meiner Chefin." },
{ id: "L36-v1", lesson: 36, skill: "vocab", topic: "Work vocabulary", type: "mc", q: "Der Bericht muss bis Freitag fertig sein. Wenn wir diese ___ nicht einhalten, bekommen wir Ärger.", opts: ["Frist", "Beförderung", "Kündigung", "Weiterbildung"], a: 0, why: "die Frist = deadline." },
{ id: "L36-w1", lesson: 36, skill: "writing", topic: "Participles as adjectives", type: "gap", q: "Der ___ Bericht liegt schon auf deinem Schreibtisch. (drucken)", a: ["gedruckte"], why: "Partizip II (passive/finished) as an adjective: der gedruckte Bericht." },
{ id: "L36-w2", lesson: 36, skill: "writing", topic: "lassen (having something done)", type: "tr", en: "Last week I had my laptop repaired.", hint: "Perfekt", de: "Letzte Woche habe ich meinen Laptop reparieren lassen.", alt: ["Ich habe letzte Woche meinen Laptop reparieren lassen.", "Ich habe meinen Laptop letzte Woche reparieren lassen.", "Vergangene Woche habe ich meinen Laptop reparieren lassen.", "Ich habe vergangene Woche meinen Laptop reparieren lassen.", "Ich habe meinen Laptop vergangene Woche reparieren lassen."], why: "Having something done: infinitive + lassen; Perfekt: habe … reparieren lassen (not gelassen)." },

// ---------- Reading ----------
{ id: "L31-r1", lesson: 31, skill: "reading", topic: "Returning a faulty product", type: "mc",
  text: "Hallo Jana, stell dir vor, was mir passiert ist! Letzte Woche habe ich im Sonderangebot eine Kaffeemaschine gekauft – nur 49 Euro statt 89. Ein echtes Schnäppchen, dachte ich. Aber schon am zweiten Tag war sie defekt. Also bin ich zurück ins Geschäft gegangen. Leider konnte ich den Kassenbon nicht mehr finden, und die Angestellte an der Kasse wollte die Maschine deshalb nicht zurücknehmen. Zum Glück hatte ich mit Karte bezahlt, und auf meinem Kontoauszug konnte man den Kauf sehen. Am Ende hat mir ein Kollege von ihr eine neue Maschine gegeben. Mein Geld habe ich zwar nicht zurückbekommen, aber jetzt funktioniert alles. Ab jetzt hebe ich jeden Kassenbon auf! Liebe Grüße, Miriam",
  q: "How was Miriam's problem solved in the end?", opts: ["Her bank statement proved the purchase, and she got a new machine.", "She got her money back in cash.", "She found the receipt at home and returned the machine.", "She paid 40 euros for a repair."], a: 0 },
{ id: "L33-r1", lesson: 33, skill: "reading", topic: "Theatre review", type: "mc",
  text: "Gestern Abend war ich bei der Premiere von „Das leere Haus“ im Stadttheater. Das Stück, über das vorher schon viel geschrieben wurde, hat mir leider nicht ganz gefallen. Die Handlung ist ziemlich kompliziert: Eine Familie, in der niemand mehr miteinander spricht, trifft sich nach dem Tod der Großmutter in ihrem alten Haus. Die Schauspieler waren aber wirklich beeindruckend, besonders Lea Brandt, die die jüngste Tochter spielt. Was mich gestört hat, war die Länge: Die Aufführung hat fast vier Stunden gedauert, und einige Zuschauer sind schon in der Pause gegangen. Am Ende hat das Publikum aber lange geklatscht. Mein Tipp: Wer gute Schauspieler sehen will, sollte hingehen – aber vorher gut schlafen!",
  q: "What did the reviewer criticise?", opts: ["The performance was too long.", "The actors were weak.", "The audience didn't clap at the end.", "The plot was too simple."], a: 0 },
{ id: "L35-r1", lesson: 35, skill: "reading", topic: "Integration forum post", type: "mc",
  text: "Ich wohne seit vier Jahren in Leipzig. Am Anfang habe ich mich sehr allein gefühlt, obwohl meine Kollegen freundlich waren. Seitdem ich ehrenamtlich in einem Sportverein arbeite, ist alles anders. Jeden Samstag trainiere ich mit Kindern Basketball. Die Eltern haben mich zuerst nur auf Englisch angesprochen, aber ich habe trotzdem immer auf Deutsch geantwortet. Je mehr ich mit ihnen gesprochen habe, desto leichter ist es mir gefallen. Letztes Jahr habe ich die deutsche Staatsangehörigkeit beantragt, und nächsten Monat darf ich zum ersten Mal wählen. Mein Tipp für alle, die neu in Deutschland sind: Wartet nicht, bis ihr perfekt Deutsch sprecht – engagiert euch einfach! Daniel, 34",
  q: "What changed things for Daniel?", opts: ["Volunteering as a basketball coach for children.", "Speaking English with the parents.", "Voting in his first German election.", "Waiting until his German was perfect."], a: 0 },
{ id: "L36-r1", lesson: 36, skill: "reading", topic: "Email about new work rules", type: "mc",
  text: "Liebes Team, wie ihr wisst, haben wir in den letzten Monaten sehr viele Überstunden gemacht. Ich bin der Meinung, dass das so nicht weitergehen kann. Deshalb gibt es ab März neue Regeln: Jeder darf zwei Tage pro Woche im Homeoffice arbeiten. Die Arbeitszeiten sind flexibel, aber zwischen 10 und 15 Uhr solltet ihr erreichbar sein. Unsere Besprechung am Montag findet ab jetzt als Videokonferenz statt. Außerdem lassen wir die neuen Laptops von einer Firma einrichten, damit ihr dafür nicht selbst Zeit verlieren müsst. Wer Ideen für eine bessere Zusammenarbeit hat, kann mir gern schreiben. Ich freue mich auf unsere gemeinsamen Ergebnisse! Viele Grüße, Katrin Vogel",
  q: "Which of these is one of the new rules?", opts: ["Employees must be reachable between 10 am and 3 pm.", "Everyone may work from home every day.", "Each employee has to set up the new laptop themselves.", "The Monday meeting will now take place in the office."], a: 0 },

// ---------- Listening ----------
{ id: "L32-l1", lesson: 32, skill: "listening", topic: "entweder … oder", type: "mc", audio: "Entweder rufst du sie an, oder du schreibst ihr eine Nachricht.", q: "What does the speaker suggest?", opts: ["Call her or send her a message.", "Neither call her nor write to her.", "Both call her and write to her.", "Wait until she calls."], a: 0 },
{ id: "L34-l1", lesson: 34, skill: "listening", topic: "Futur I (predictions)", type: "mc", audio: "Ich glaube, es wird heißer werden, aber wir werden auch viel mehr erneuerbare Energie nutzen.", q: "What does the speaker predict?", opts: ["It will get hotter, but much more renewable energy will be used.", "It will get hotter, and we will use less energy.", "It will get cooler thanks to renewable energy.", "Temperatures will stay the same."], a: 0 },
{ id: "L35-l1", lesson: 35, skill: "listening", topic: "Time clauses: seitdem", type: "mc", audio: "Seitdem mein Sohn in die Schule geht, helfe ich ehrenamtlich im Elternverein.", q: "Since when has the speaker been volunteering?", opts: ["Since their son started school.", "Since their son finished school.", "Since they moved to a new city.", "Since the last election."], a: 0 },
{ id: "L31-l1", lesson: 31, skill: "listening", topic: "Perfekt of ausgeben", type: "dict", audio: "Für das Auto haben wir fast alle Ersparnisse ausgegeben.", q: "Für das Auto haben wir fast alle Ersparnisse ___.", a: ["ausgegeben"] },
{ id: "L36-l1", lesson: 36, skill: "listening", topic: "Participles as adjectives", type: "dict", audio: "Ich habe die erledigten Aufgaben schon an alle geschickt.", q: "Ich habe die ___ Aufgaben schon an alle geschickt.", a: ["erledigten"] }
);
