// Level exam items, lessons 37-42, written for this app.
EXAM.push(
// ---------- Lesson 37: Konjunktiv I, reported speech ----------
{ id: "L37-g1", lesson: 37, skill: "grammar", topic: "Konjunktiv I (past)", type: "mc", q: "Der Sprecher erklärte, der Minister ___ bereits zurückgetreten.", opts: ["sei", "habe", "werde", "solle"], a: 0, why: "Past in reported speech = Konjunktiv I of the Perfekt auxiliary; zurücktreten takes sein, so: sei zurückgetreten." },
{ id: "L37-g2", lesson: 37, skill: "grammar", topic: "Konjunktiv II as substitute", type: "mc", q: "In der Mitteilung heißt es, die Mitarbeiter ___ von den Plänen nichts gewusst.", opts: ["hätten", "habe", "hatte", "seien"], a: 0, why: "Plural Konjunktiv I 'haben' looks like the indicative, so reported speech switches to Konjunktiv II: sie hätten." },
{ id: "L37-g3", lesson: 37, skill: "grammar", topic: "Reported questions (ob)", type: "mc", q: "Die Chefin wollte wissen, ___ wir den Bericht schon abgeschickt hätten.", opts: ["ob", "dass", "wenn", "falls"], a: 0, why: "A reported yes/no question is introduced by ob (English 'if/whether'), not wenn." },
{ id: "L37-v1", lesson: 37, skill: "vocab", topic: "Communication verbs", type: "mc", q: "Die Pressesprecherin wollte sich zu den Gerüchten nicht ___.", opts: ["äußern", "erwähnen", "behaupten", "mitteilen"], a: 0, why: "sich zu etwas äußern = to comment on something; none of the other verbs combine with sich zu + Dativ." },
{ id: "L37-w1", lesson: 37, skill: "writing", topic: "Konjunktiv I (past)", type: "gap", q: "Laut Polizei ___ der Fahrer viel zu schnell ___. (fahren, Konjunktiv I)", a: ["sei", "gefahren"], why: "Reported past: Konjunktiv I of the auxiliary + Partizip II; fahren takes sein: sei gefahren." },
{ id: "L37-w2", lesson: 37, skill: "writing", topic: "Konjunktiv I (past)", type: "tr", en: "My colleague (female) claims that she was ill yesterday.", hint: "use Konjunktiv I", de: "Meine Kollegin behauptet, sie sei gestern krank gewesen.", alt: ["Meine Kollegin behauptet, dass sie gestern krank gewesen sei.", "Meine Kollegin behauptet, gestern krank gewesen zu sein."], why: "Reported past state: sie sei ... gewesen." },

// ---------- Lesson 38: Nominalisierung, Nomen-Verb-Verbindungen ----------
{ id: "L38-g1", lesson: 38, skill: "grammar", topic: "Nominal style: trotz + Genitiv", type: "mc", q: "___ des starken Winds fand die Betriebsfeier wie geplant draußen statt.", opts: ["Trotz", "Wegen", "Nach", "Bei"], a: 0, why: "obwohl es windig war → trotz + Genitiv: trotz des starken Winds." },
{ id: "L38-g2", lesson: 38, skill: "grammar", topic: "Nominal style: adverb → adjective", type: "mc", q: "Wegen ihrer ___ Reaktion konnte der Schaden begrenzt werden.", opts: ["schnellen", "schnelle", "schnell", "schnelles"], a: 0, why: "In a noun phrase the adverb becomes an adjective; feminine genitive after ihrer takes -en: ihrer schnellen Reaktion." },
{ id: "L38-g3", lesson: 38, skill: "grammar", topic: "Nomen-Verb-Verbindungen", type: "mc", q: "Mehrere Mitarbeiter ___ offen Kritik an den Plänen des Vorstands.", opts: ["übten", "machten", "stellten", "trafen"], a: 0, why: "The fixed combination is Kritik üben (an + Dativ)." },
{ id: "L38-v1", lesson: 38, skill: "vocab", topic: "Career expressions", type: "mc", q: "Eine Stelle in einer anderen Stadt kommt für mich im Moment nicht ___.", opts: ["infrage", "zur Verfügung", "zum Vorschlag", "Bescheid"], a: 0, why: "infrage kommen = to be an option." },
{ id: "L38-w1", lesson: 38, skill: "writing", topic: "Noun formation (-ung)", type: "gap", q: "Nach ihrer ___ zur Teamleiterin verdient sie deutlich mehr. (befördern)", a: ["Beförderung"], why: "nachdem sie befördert wurde → nach ihrer Beförderung (verb + -ung)." },
{ id: "L38-w2", lesson: 38, skill: "writing", topic: "Nominal style: trotz", type: "tr", en: "Despite his experience, he didn't get the leadership position.", hint: "use trotz", de: "Trotz seiner Erfahrung hat er die Führungsposition nicht bekommen.", alt: ["Trotz seiner Erfahrung bekam er die Führungsposition nicht.", "Trotz seiner Erfahrung hat er die Führungsposition nicht erhalten.", "Trotz seiner Erfahrung erhielt er die Führungsposition nicht.", "Er hat die Führungsposition trotz seiner Erfahrung nicht bekommen.", "Er bekam die Führungsposition trotz seiner Erfahrung nicht.", "Er hat trotz seiner Erfahrung die Führungsposition nicht bekommen.", "Er bekam trotz seiner Erfahrung die Führungsposition nicht.", "Er hat die Führungsposition trotz seiner Erfahrung nicht erhalten.", "Er erhielt die Führungsposition trotz seiner Erfahrung nicht.", "Er hat trotz seiner Erfahrung die Führungsposition nicht erhalten.", "Er erhielt trotz seiner Erfahrung die Führungsposition nicht."], why: "trotz + Genitiv: trotz seiner Erfahrung." },

// ---------- Lesson 39: sich lassen, -bar/-lich, sein + zu ----------
{ id: "L39-g1", lesson: 39, skill: "grammar", topic: "sich lassen + Infinitiv", type: "mc", q: "Mit der neuen Software lässt sich der Fehler in wenigen Minuten ___.", opts: ["finden", "gefunden", "zu finden", "findet"], a: 0, why: "sich lassen takes a plain infinitive without zu: lässt sich finden." },
{ id: "L39-g2", lesson: 39, skill: "grammar", topic: "Adjectives in -bar/-lich", type: "mc", q: "Das neue Gerät ist ab nächster Woche in allen Geschäften ___.", opts: ["erhältlich", "erhaltbar", "erhältig", "haltbar"], a: 0, why: "'Can be bought/obtained' = erhältlich (-lich, not -bar)." },
{ id: "L39-g3", lesson: 39, skill: "grammar", topic: "sein + zu + Infinitiv", type: "mc", q: "Das Formular ist bis Montag vollständig ___.", opts: ["auszufüllen", "zu ausfüllen", "ausgefüllt zu", "ausfüllen"], a: 0, why: "sein + zu + infinitive = must be done; with separable verbs zu goes in the middle: auszufüllen." },
{ id: "L39-v1", lesson: 39, skill: "vocab", topic: "Technology vocabulary", type: "mc", q: "Viele Menschen haben Angst, dass Roboter eines Tages ihre Arbeit ___ werden.", opts: ["ersetzen", "entdecken", "erfinden", "entwickeln"], a: 0, why: "ersetzen = to replace." },
{ id: "L39-w1", lesson: 39, skill: "writing", topic: "sich lassen + Infinitiv", type: "gap", q: "Diese Hypothese ___ sich leider nicht ___. (sich lassen + beweisen)", a: ["lässt/ließ", "beweisen"], why: "'Can't be proven' = lässt sich nicht beweisen (infinitive, not participle)." },
{ id: "L39-w2", lesson: 39, skill: "writing", topic: "sich lassen + Infinitiv", type: "tr", en: "The new algorithm can't easily be explained.", hint: "use sich lassen", de: "Der neue Algorithmus lässt sich nicht leicht erklären.", alt: ["Der neue Algorithmus lässt sich nicht einfach erklären.", "Der neue Algorithmus lässt sich nicht so leicht erklären.", "Der neue Algorithmus lässt sich nicht so einfach erklären.", "Der neue Algorithmus ist nicht leicht zu erklären.", "Der neue Algorithmus ist nicht einfach zu erklären.", "Den neuen Algorithmus kann man nicht leicht erklären.", "Den neuen Algorithmus kann man nicht einfach erklären.", "Der neue Algorithmus kann nicht leicht erklärt werden.", "Man kann den neuen Algorithmus nicht leicht erklären.", "Man kann den neuen Algorithmus nicht einfach erklären."], why: "lässt sich + infinitive = can be done." },

// ---------- Lesson 40: participles as adjectives ----------
{ id: "L40-g1", lesson: 40, skill: "grammar", topic: "Partizip I as adjective", type: "mc", q: "Nach einem sehr ___ Arbeitstag kann ich oft nicht einschlafen.", opts: ["belastenden", "belasteten", "belastende", "belastendem"], a: 0, why: "The day causes stress (active) → Partizip I; dative masculine after einem: belastenden." },
{ id: "L40-g2", lesson: 40, skill: "grammar", topic: "Partizip II as adjective", type: "mc", q: "Die gestern ___ Studie zeigt, dass Schlafmangel die Konzentration verringert.", opts: ["veröffentlichte", "veröffentlichende", "veröffentlicht", "veröffentlichten"], a: 0, why: "The study was published (passive, completed) → Partizip II with ending: die veröffentlichte Studie." },
{ id: "L40-g3", lesson: 40, skill: "grammar", topic: "Extended participle attributes", type: "mc", q: "Die ___ Therapie hat ihr sehr geholfen.", opts: ["von ihrer Ärztin vorgeschlagene", "vorgeschlagene von ihrer Ärztin", "von ihrer Ärztin vorschlagende", "von ihrer Ärztin vorgeschlagenen"], a: 0, why: "All extra information goes before the participle; the therapy was suggested (Partizip II), nominative feminine after die: -e." },
{ id: "L40-v1", lesson: 40, skill: "vocab", topic: "Stress and mental health", type: "mc", q: "Wenn ich zu wenig schlafe, bin ich am nächsten Tag schnell ___ und streite mit allen.", opts: ["reizbar", "ausgeglichen", "erholt", "achtsam"], a: 0, why: "reizbar = irritable." },
{ id: "L40-w1", lesson: 40, skill: "writing", topic: "Partizip I with ending", type: "gap", q: "Die seit Monaten ___ Belastung macht viele Mitarbeiter krank. (wachsen, Partizip I)", a: ["wachsende"], why: "Something happening now → Partizip I (infinitive + d) with adjective ending: die ... wachsende Belastung." },
{ id: "L40-w2", lesson: 40, skill: "writing", topic: "Extended participle attributes", type: "tr", en: "The number of people suffering from anxiety disorders is rising.", hint: "use a participle before the noun", de: "Die Zahl der an Angststörungen leidenden Menschen steigt.", alt: ["Die Zahl der unter Angststörungen leidenden Menschen steigt.", "Die Zahl der an Angststörungen leidenden Menschen nimmt zu.", "Die Zahl der unter Angststörungen leidenden Menschen nimmt zu.", "Die Zahl der Menschen, die an Angststörungen leiden, steigt.", "Die Zahl der Menschen, die unter Angststörungen leiden, steigt.", "Die Zahl der Menschen, die an Angststörungen leiden, nimmt zu.", "Die Zahl der Menschen, die unter Angststörungen leiden, nimmt zu.", "Die Zahl der an Angststörungen leidenden Menschen wächst.", "Die Zahl der unter Angststörungen leidenden Menschen wächst."], why: "Menschen, die an ... leiden → die an ... leidenden Menschen." },

// ---------- Lesson 41: indem/sodass, ohne ... zu, statt ... zu ----------
{ id: "L41-g1", lesson: 41, skill: "grammar", topic: "indem vs. sodass", type: "mc", q: "Sie hat das Problem mit der Behörde gelöst, ___ sie einfach dort angerufen hat.", opts: ["indem", "sodass", "damit", "ohne"], a: 0, why: "How did she solve it? By calling → indem (means), not sodass (result)." },
{ id: "L41-g2", lesson: 41, skill: "grammar", topic: "ohne dass (different subjects)", type: "mc", q: "Er hat die Wohnung verlassen, ___ seine Mitbewohner es bemerkt haben.", opts: ["ohne dass", "ohne", "statt", "indem"], a: 0, why: "Different subjects in the two parts → ohne dass + full clause." },
{ id: "L41-g3", lesson: 41, skill: "grammar", topic: "statt ... zu: word order", type: "mc", q: "Statt sich über die Bürokratie zu beschweren, ___.", opts: ["hat sie alle Formulare sofort ausgefüllt", "sie hat alle Formulare sofort ausgefüllt", "sie alle Formulare sofort ausgefüllt hat", "hat alle Formulare sie sofort ausgefüllt"], a: 0, why: "The statt ... zu clause is position 1, so the finite verb comes next, then the subject." },
{ id: "L41-v1", lesson: 41, skill: "vocab", topic: "Migration vocabulary", type: "mc", q: "Am Anfang war im neuen Land alles ungewohnt und fremd – ich hatte einen richtigen ___.", opts: ["Kulturschock", "Abschied", "Akzent", "Neuanfang"], a: 0, why: "der Kulturschock = culture shock." },
{ id: "L41-w1", lesson: 41, skill: "writing", topic: "ohne ... zu (separable verb)", type: "gap", q: "Wir haben den Mietvertrag unterschrieben, ohne die Wohnung vorher ___. (ansehen)", a: ["anzusehen"], why: "Same subject → ohne ... zu + infinitive; with separable verbs zu goes between prefix and stem: anzusehen." },
{ id: "L41-w2", lesson: 41, skill: "writing", topic: "statt ... zu", type: "tr", en: "Instead of speaking English everywhere, she tries to speak German with locals.", hint: "start with Statt", de: "Statt überall Englisch zu sprechen, versucht sie, mit Einheimischen Deutsch zu sprechen.", alt: ["Anstatt überall Englisch zu sprechen, versucht sie, mit Einheimischen Deutsch zu sprechen.", "Statt überall Englisch zu sprechen, versucht sie, Deutsch mit Einheimischen zu sprechen.", "Anstatt überall Englisch zu sprechen, versucht sie, Deutsch mit Einheimischen zu sprechen.", "Statt überall Englisch zu sprechen, versucht sie mit Einheimischen Deutsch zu sprechen.", "Anstatt überall Englisch zu sprechen, versucht sie mit Einheimischen Deutsch zu sprechen.", "Statt überall Englisch zu sprechen, versucht sie Deutsch mit Einheimischen zu sprechen.", "Sie versucht, mit Einheimischen Deutsch zu sprechen, statt überall Englisch zu sprechen.", "Sie versucht, mit Einheimischen Deutsch zu sprechen, anstatt überall Englisch zu sprechen."], why: "The statt ... zu clause comes first, so the verb (versucht) follows immediately." },

// ---------- Lesson 42: sollen/wollen, modal assumptions, Futur II ----------
{ id: "L42-g1", lesson: 42, skill: "grammar", topic: "wollen for claims", type: "mc", q: "Mein Nachbar ___ mit nur 15 Jahren das Abitur gemacht haben, aber das glaube ich ihm nicht.", opts: ["will", "muss", "dürfte", "kann"], a: 0, why: "wollen + Partizip II + haben = the subject claims this about himself (sceptical)." },
{ id: "L42-g2", lesson: 42, skill: "grammar", topic: "Modal verbs for assumptions", type: "mc", q: "Das Licht im Büro ist aus und ihr Auto ist weg. Sie ___ schon nach Hause gegangen sein.", opts: ["muss", "kann nicht", "will", "darf"], a: 0, why: "Strong evidence → müssen for an almost certain assumption: Sie muss gegangen sein." },
{ id: "L42-g3", lesson: 42, skill: "grammar", topic: "Futur II (haben/sein)", type: "mc", q: "Die Klausur war leicht – die meisten Studierenden werden sie wohl bestanden ___.", opts: ["haben", "sein", "werden", "hätten"], a: 0, why: "Futur II = werden + Partizip II + haben/sein as in the Perfekt: bestanden haben." },
{ id: "L42-v1", lesson: 42, skill: "vocab", topic: "Education vocabulary", type: "mc", q: "Wer seinen Schulabschluss erst als Erwachsener ___, besucht oft eine Abendschule.", opts: ["nachholt", "durchfällt", "vermittelt", "fördert"], a: 0, why: "etwas nachholen = to catch up on / make up for something later." },
{ id: "L42-w1", lesson: 42, skill: "writing", topic: "Futur II (completed by a future time)", type: "gap", q: "Bis Ende des Jahres ___ sie ihr Studium ___ haben. (abschließen)", a: ["wird/werden", "abgeschlossen"], why: "Futur II = werden + Partizip II + haben: wird abgeschlossen haben." },
{ id: "L42-w2", lesson: 42, skill: "writing", topic: "sollen for reports (past)", type: "tr", en: "He is said to have failed the exam twice.", hint: "use sollen", de: "Er soll zweimal durch die Prüfung gefallen sein.", alt: ["Er soll zweimal bei der Prüfung durchgefallen sein.", "Er soll die Prüfung zweimal nicht bestanden haben.", "Er soll zweimal durch die Prüfung durchgefallen sein.", "Er soll zweimal in der Prüfung durchgefallen sein.", "Er soll bei der Prüfung zweimal durchgefallen sein.", "Er soll die Prüfung zweimal nicht geschafft haben."], why: "sollen + Partizip II + sein/haben = it is said that he did it: soll ... gefallen sein." },

// ---------- Reading ----------
{ id: "L37-r1", lesson: 37, skill: "reading", topic: "Reading: news with reported speech", type: "mc",
  text: "Seit Wochen gab es unter den Mitarbeitern eines Münchner Softwareunternehmens ein Gerücht: Die Firma werde an einen amerikanischen Konzern verkauft, viele Stellen seien in Gefahr. Am Montag hat sich nun die Geschäftsführerin dazu geäußert. In einer Mitteilung an alle Mitarbeiter betonte sie, es gebe keine Verkaufspläne. Man habe zwar Gespräche mit einem Partner aus den USA geführt, dabei sei es aber nur um ein gemeinsames Forschungsprojekt gegangen. Entlassungen seien nicht geplant, im Gegenteil: Das Unternehmen wachse und suche sogar neue Fachkräfte. Auch die Gerüchte über einen Umzug nach Berlin wies sie zurück. Einige Mitarbeiter zeigten sich trotzdem skeptisch. Ein Teamleiter erklärte, man habe zu spät und zu ausweichend informiert. Die Mitarbeiter hätten ein Recht darauf, früher zu erfahren, was die Firmenleitung plane.",
  q: "According to the managing director, what were the talks with the US partner about?",
  opts: ["A joint research project", "Selling the company", "Cutting jobs", "Moving the company to the USA"], a: 0 },
{ id: "L39-r1", lesson: 39, skill: "reading", topic: "Reading: article on AI in medicine", type: "mc",
  text: "In einem Krankenhaus in Haifa testen Ärzte und Informatiker seit einem Jahr eine neue Software. Sie wertet Röntgenbilder aus und markiert Stellen, die auf eine Krankheit hindeuten könnten. Die ersten Ergebnisse sind beeindruckend: Viele Tumore lassen sich mit der Software früher erkennen als mit bloßem Auge. Trotzdem betonen die Forscher, dass die KI die Ärzte nicht ersetzen soll. Jede Diagnose ist weiterhin von einem Arzt zu prüfen, denn auch der Algorithmus macht Fehler, und warum er zu einem bestimmten Ergebnis kommt, ist nicht immer nachvollziehbar. Ein weiteres Problem ist der Datenschutz: Für das Training braucht das System sehr viele Patientendaten, die besonders gut zu schützen sind. Ob die Software bald in allen Kliniken des Landes eingesetzt wird, ist deshalb noch nicht vorhersehbar.",
  q: "What do the researchers say about the role of doctors?",
  opts: ["Every diagnosis must still be checked by a doctor.", "The software will soon replace doctors.", "Doctors no longer need to look at X-rays.", "The algorithm never makes mistakes."], a: 0 },
{ id: "L40-r1", lesson: 40, skill: "reading", topic: "Reading: forum post on sleep", type: "mc",
  text: "Hallo zusammen, ich (34) arbeite als Projektleiterin in einer IT-Firma und fühle mich seit Monaten völlig erschöpft. Das Einschlafen ist kein Problem, aber gegen drei Uhr wache ich auf und denke an die vielen unbeantworteten E-Mails. Danach kann ich meistens nicht mehr einschlafen. Tagsüber bin ich reizbar und kann mich kaum konzentrieren. Meine Hausärztin meint, die Ursache sei wohl nicht körperlich, sondern der ständig wachsende Druck im Job. Sie hat mir geraten, abends das Handy auszuschalten und als Ausgleich mehr Sport zu machen. Die von ihr empfohlenen Entspannungsübungen habe ich ausprobiert, aber sie helfen mir bisher nur wenig. Eine Therapie möchte ich eigentlich vermeiden, weil ich glaube, dass ich das Problem allein bewältigen kann. Hat jemand Erfahrung mit diesem Problem? Was hat euch geholfen, wieder durchzuschlafen? Danke! Mira",
  q: "What is Mira's main sleep problem?",
  opts: ["She wakes up around three and can't get back to sleep.", "She can't fall asleep in the evening.", "She sleeps too long in the morning.", "She sleeps well but feels tired because of physical illness."], a: 0 },
{ id: "L41-r1", lesson: 41, skill: "reading", topic: "Reading: personal story about emigrating", type: "mc",
  text: "Als ich vor acht Jahren von Tel Aviv nach Leipzig gezogen bin, konnte ich kaum Deutsch. Die ersten Monate waren so schwierig, dass ich fast wieder zurückgeflogen wäre. Die Bürokratie, das graue Wetter, die fremden Gewohnheiten – an alles musste ich mich erst gewöhnen. Statt nur mit anderen Israelis Zeit zu verbringen, bin ich dann in einen Chor eingetreten. Dort habe ich schnell Kontakte zu Einheimischen geknüpft und mein Deutsch verbessert, indem ich jede Woche mit ihnen gesungen und geredet habe. Heute arbeite ich als Lehrerin, und meine Kinder wachsen zweisprachig auf. Trotzdem habe ich manchmal Sehnsucht nach dem Meer und nach dem Lärm auf den Märkten. Fühle ich mich in Deutschland zugehörig? Meistens ja. Aber Heimat ist für mich nicht ein Ort, sondern zwei.",
  q: "How did the writer improve her German?",
  opts: ["By singing and talking with locals in a choir every week", "By spending her free time mainly with other Israelis", "She didn't need to: she already spoke good German before moving"], a: 0 },

// ---------- Listening ----------
{ id: "L38-l1", lesson: 38, skill: "listening", topic: "Listening: career priorities", type: "mc", audio: "Für mich spielt die Verantwortung eine größere Rolle als das Gehalt, solange es fair ist.", q: "What matters more to the speaker?", opts: ["Responsibility, as long as the salary is fair", "A high salary", "Fast promotion", "Working fewer hours"], a: 0 },
{ id: "L41-l1", lesson: 41, skill: "listening", topic: "Listening: culture shock", type: "mc", audio: "Ja, in Deutschland war ich überrascht, dass am Sonntag fast alle Geschäfte geschlossen sind.", q: "What surprised the speaker in Germany?", opts: ["Almost all shops are closed on Sundays.", "Shops are open all night.", "Almost everyone works on Sundays.", "Shops close early on Fridays."], a: 0 },
{ id: "L42-l1", lesson: 42, skill: "listening", topic: "Listening: school systems", type: "mc", audio: "In Deutschland werden Kinder schon nach der vierten Klasse auf verschiedene Schulen verteilt, während in Israel alle länger zusammen lernen.", q: "What does the speaker say about Germany?", opts: ["Children are sent to different schools after fourth grade.", "All children learn together until the end of school.", "Children start school at the age of four.", "Israel separates children earlier than Germany."], a: 0 },
{ id: "L39-l1", lesson: 39, skill: "listening", topic: "Listening: sich lassen", type: "dict", audio: "Manche Aufgaben lassen sich durch KI ersetzen, aber Kreativität und Empathie sind schwer zu automatisieren.", q: "Manche Aufgaben ___ sich durch KI ersetzen, aber Kreativität und Empathie sind schwer zu automatisieren.", a: ["lassen"] },
{ id: "L40-l1", lesson: 40, skill: "listening", topic: "Listening: Partizip I", type: "dict", audio: "Die seit Jahren steigende Zahl der Burn-out-Fälle ist alarmierend.", q: "Die seit Jahren ___ Zahl der Burn-out-Fälle ist alarmierend.", a: ["steigende"] }
);
