// Level exam items, lessons 43-48, written for this app.
EXAM.push(
// ---------- Lesson 43: Nachhaltigkeit ----------
{ id: "L43-g1", lesson: 43, skill: "grammar", topic: "Concession with trotz + Genitiv", type: "mc", q: "___ der hohen Preise kaufen viele Familien Bio-Produkte.", opts: ["Obwohl", "Trotzdem", "Trotz", "Zwar"], a: 2, why: "Before a noun phrase you need the preposition trotz + genitive; obwohl and trotzdem introduce clauses." },
{ id: "L43-g2", lesson: 43, skill: "grammar", topic: "Word order after a concessive clause", type: "mc", q: "Obwohl die Solaranlage teuer war, ___.", opts: ["sie hat sich gelohnt", "hat sie sich gelohnt", "sie sich gelohnt hat", "hat sich sie gelohnt"], a: 1, why: "When the obwohl clause comes first, it fills position 1, so the main clause starts with the verb." },
{ id: "L43-g3", lesson: 43, skill: "grammar", topic: "Argument phrases: einerseits … andererseits", type: "mc", q: "Einerseits spart man mit dem Fahrrad Zeit, ___ ist es im Sommer oft sehr heiß.", opts: ["zum anderen", "andererseits", "zweitens", "anders"], a: 1, why: "einerseits is always paired with andererseits (zum einen goes with zum anderen)." },
{ id: "L43-v1", lesson: 43, skill: "vocab", topic: "Environment vocabulary", type: "mc", q: "Der ___ an Wasser ist in heißen Sommern besonders hoch.", opts: ["Verzicht", "Ausstoß", "Verbrauch", "Fußabdruck"], a: 2, why: "der Verbrauch an … = the consumption of …" },
{ id: "L43-w1", lesson: 43, skill: "writing", type: "gap", topic: "obwohl clause + verb-first main clause", q: "Obwohl die Maßnahmen umstritten ___, ___ die Regierung sie letzte Woche beschlossen. (sein, haben)", a: ["waren/sind", "hat"], why: "obwohl sends the verb to the end; the main clause after it starts with the verb." },
{ id: "L43-w2", lesson: 43, skill: "writing", type: "tr", topic: "zwar … aber", en: "Admittedly, regional vegetables are more expensive, but they taste better.", hint: "use zwar … aber", de: "Regionales Gemüse ist zwar teurer, aber es schmeckt besser.", alt: ["Zwar ist regionales Gemüse teurer, aber es schmeckt besser.", "Regionales Gemüse ist zwar teurer, schmeckt aber besser.", "Regionales Gemüse ist zwar teurer, aber schmeckt besser.", "Regionales Gemüse ist zwar teurer, es schmeckt aber besser.", "Das regionale Gemüse ist zwar teurer, schmeckt aber besser.", "Das regionale Gemüse ist zwar teurer, aber es schmeckt besser.", "Zwar ist das regionale Gemüse teurer, aber es schmeckt besser."], why: "zwar sits in the first clause, aber opens the second." },

// ---------- Lesson 44: Medien und Wahrheit ----------
{ id: "L44-g1", lesson: 44, skill: "grammar", topic: "Modal particle wohl", type: "mc", q: "Sein Auto ist nicht mehr da. Er ist ___ schon nach Hause gefahren. (I suppose)", opts: ["doch", "wohl", "halt", "mal"], a: 1, why: "wohl marks an assumption: 'probably, I suppose'." },
{ id: "L44-g2", lesson: 44, skill: "grammar", topic: "Position of modal particles", type: "mc", q: "Wir können daran nichts ändern, ___.", opts: ["das ist halt so", "halt ist das so", "das halt ist so", "das ist so halt"], a: 0, why: "Modal particles stand in the middle field after the verb, never in position 1." },
{ id: "L44-g3", lesson: 44, skill: "grammar", topic: "Focus words (sogar, erst, nur)", type: "mc", q: "Die Falschmeldung war so gut gemacht, dass ___ Experten darauf hereingefallen sind.", opts: ["erst", "nur", "sogar", "noch"], a: 2, why: "sogar = 'even': it points to a surprising extreme case." },
{ id: "L44-v1", lesson: 44, skill: "vocab", topic: "Media vocabulary", type: "mc", q: "Bevor du einen Artikel teilst, solltest du die Quelle ___.", opts: ["verbreiten", "überprüfen", "manipulieren", "auftauchen"], a: 1, why: "eine Quelle überprüfen = to check a source." },
{ id: "L44-w1", lesson: 44, skill: "writing", type: "gap", topic: "Separable verb auftauchen (Präteritum)", q: "Gestern ___ in den sozialen Medien ein gefälschtes Interview ___. (auftauchen, Präteritum)", a: ["tauchte", "auf"], why: "auftauchen is separable: the prefix auf goes to the end." },
{ id: "L44-w2", lesson: 44, skill: "writing", type: "tr", topic: "Focus word sogar", en: "Even reputable newspapers did not check the source.", hint: "Perfekt", de: "Sogar seriöse Zeitungen haben die Quelle nicht überprüft.", alt: ["Selbst seriöse Zeitungen haben die Quelle nicht überprüft.", "Sogar seriöse Zeitungen haben die Quelle nicht geprüft.", "Selbst seriöse Zeitungen haben die Quelle nicht geprüft.", "Sogar seriöse Zeitungen haben die Quelle nicht kontrolliert.", "Selbst seriöse Zeitungen haben die Quelle nicht kontrolliert."], why: "even = sogar / selbst, placed right before the word it highlights." },

// ---------- Lesson 45: Wirtschaft ----------
{ id: "L45-g1", lesson: 45, skill: "grammar", topic: "Nomen-Verb-Verbindung: eine Entscheidung treffen", type: "mc", q: "Der Vorstand hat gestern eine wichtige Entscheidung ___.", opts: ["gemacht", "getroffen", "gestellt", "genommen"], a: 1, why: "German says eine Entscheidung treffen, never 'machen'." },
{ id: "L45-g2", lesson: 45, skill: "grammar", topic: "in Frage kommen vs. in Frage stellen", type: "mc", q: "Ein Umzug nach Haifa ___ für uns im Moment leider nicht in Frage.", opts: ["stellt", "kommt", "steht", "nimmt"], a: 1, why: "in Frage kommen = to be a possible option; in Frage stellen = to doubt." },
{ id: "L45-g3", lesson: 45, skill: "grammar", topic: "zur Verfügung stehen vs. stellen", type: "mc", q: "Den neuen Mitarbeitern ___ ab Montag moderne Laptops zur Verfügung.", opts: ["stellen", "stehen", "bringen", "kommen"], a: 1, why: "The laptops are the subject (nothing 'does' it), so it is zur Verfügung stehen, not stellen." },
{ id: "L45-v1", lesson: 45, skill: "vocab", topic: "Economy vocabulary", type: "mc", q: "Die ___ nach Fahrrädern ist während der Pandemie stark gestiegen.", opts: ["Konjunktur", "Branche", "Nachfrage", "Zielgruppe"], a: 2, why: "die Nachfrage nach … = demand for …" },
{ id: "L45-w1", lesson: 45, skill: "writing", type: "gap", topic: "Nomen-Verb-Verbindung: in Kauf nehmen", q: "Meine Schwester ___ für ihren Traumjob einen langen Arbeitsweg in ___. (to put up with)", a: ["nimmt/nahm", "Kauf"], why: "in Kauf nehmen: the verb is in position 2, 'in Kauf' goes to the end." },
{ id: "L45-w2", lesson: 45, skill: "writing", type: "tr", topic: "Nomen-Verb-Verbindung: in Frage stellen", en: "The investors have called our business plan into question.", de: "Die Investoren haben unseren Businessplan in Frage gestellt.", alt: ["Die Investoren haben unseren Businessplan infrage gestellt.", "Die Investoren haben unseren Geschäftsplan in Frage gestellt.", "Die Investoren haben unseren Geschäftsplan infrage gestellt.", "Die Investoren stellten unseren Businessplan in Frage.", "Die Investoren stellten unseren Businessplan infrage.", "Die Investoren stellten unseren Geschäftsplan in Frage.", "Die Investoren stellten unseren Geschäftsplan infrage."], why: "to call into question = in Frage stellen (also spelled infrage)." },

// ---------- Lesson 46: Kunst und Kultur ----------
{ id: "L46-g1", lesson: 46, skill: "grammar", topic: "Prepositions with the genitive", type: "mc", q: "Aufgrund ___ starken Regens wurde das Open-Air-Konzert abgesagt.", opts: ["dem", "den", "des", "der"], a: 2, why: "aufgrund takes the genitive: masculine des starken Regens." },
{ id: "L46-g2", lesson: 46, skill: "grammar", topic: "wer … dem (general relative clause)", type: "mc", q: "Wer gern ins Theater geht, ___ kann ich dieses Festival nur empfehlen.", opts: ["der", "dem", "den", "wem"], a: 1, why: "empfehlen needs a dative person, so the main clause picks up wer with dem." },
{ id: "L46-g3", lesson: 46, skill: "grammar", topic: "was referring to a whole clause", type: "mc", q: "Alle Karten waren schon nach zwei Tagen verkauft, ___ selbst die Veranstalter überrascht hat.", opts: ["das", "die", "was", "wer"], a: 2, why: "A relative clause about the whole previous clause starts with was." },
{ id: "L46-v1", lesson: 46, skill: "vocab", topic: "Describing art", type: "mc", q: "Auf den ersten Blick ___ das Bild ganz einfach, aber es steckt viel dahinter.", opts: ["betrachtet", "wirkt", "stellt", "inszeniert"], a: 1, why: "wirken = to seem, to come across." },
{ id: "L46-w1", lesson: 46, skill: "writing", type: "gap", topic: "außerhalb + Genitiv", q: "Außerhalb ___ Hauptsaison ist das Museum montags geschlossen. (die Hauptsaison)", a: ["der"], why: "außerhalb takes the genitive: feminine die → der." },
{ id: "L46-w2", lesson: 46, skill: "writing", type: "tr", topic: "wer clause + innerhalb", en: "Whoever wants to see the exhibition has to buy a ticket within a week.", hint: "start with Wer", de: "Wer die Ausstellung sehen will, muss innerhalb einer Woche eine Karte kaufen.", alt: ["Wer die Ausstellung sehen möchte, muss innerhalb einer Woche eine Karte kaufen.", "Wer die Ausstellung sehen will, der muss innerhalb einer Woche eine Karte kaufen.", "Wer die Ausstellung sehen möchte, der muss innerhalb einer Woche eine Karte kaufen.", "Wer die Ausstellung sehen will, muss innerhalb einer Woche ein Ticket kaufen.", "Wer die Ausstellung sehen möchte, muss innerhalb einer Woche ein Ticket kaufen.", "Wer die Ausstellung sehen will, der muss innerhalb einer Woche ein Ticket kaufen.", "Wer die Ausstellung sehen möchte, der muss innerhalb einer Woche ein Ticket kaufen.", "Wer die Ausstellung sehen will, muss innerhalb einer Woche eine Eintrittskarte kaufen.", "Wer die Ausstellung sehen möchte, muss innerhalb einer Woche eine Eintrittskarte kaufen.", "Wer die Ausstellung sehen will, der muss innerhalb einer Woche eine Eintrittskarte kaufen.", "Wer die Ausstellung sehen möchte, der muss innerhalb einer Woche eine Eintrittskarte kaufen."], why: "innerhalb + genitive: innerhalb einer Woche." },

// ---------- Lesson 47: Zusammenleben und Werte ----------
{ id: "L47-g1", lesson: 47, skill: "grammar", topic: "Konjunktiv II past: wäre vs. hätte", type: "mc", q: "Wenn ich nicht krank gewesen ___, wäre ich zur Hochzeit gekommen.", opts: ["hätte", "wäre", "würde", "war"], a: 1, why: "sein forms its Perfekt with sein, so the past Konjunktiv II is gewesen wäre." },
{ id: "L47-g2", lesson: 47, skill: "grammar", topic: "hätte + double infinitive", type: "mc", q: "Du hättest mir die Wahrheit sagen ___.", opts: ["gesollt", "sollen", "soll", "sollst"], a: 1, why: "With a modal verb the past Konjunktiv II uses two infinitives: hätte … sagen sollen." },
{ id: "L47-g3", lesson: 47, skill: "grammar", topic: "als (ob) + Konjunktiv II", type: "mc", q: "Sie tut so, als ___ sie von dem Streit nichts gewusst.", opts: ["hat", "wäre", "hätte", "würde"], a: 2, why: "als without ob is followed directly by the Konjunktiv II verb; wissen takes haben: hätte gewusst." },
{ id: "L47-v1", lesson: 47, skill: "vocab", topic: "Values and regrets vocabulary", type: "mc", q: "Ich ___ es bis heute, dass ich das Jobangebot in Berlin abgelehnt habe.", opts: ["verzeihe", "bereue", "respektiere", "benachteilige"], a: 1, why: "bereuen = to regret." },
{ id: "L47-w1", lesson: 47, skill: "writing", type: "gap", topic: "hätte + double infinitive", q: "Ihr ___ mich vorher fragen ___! (should have: sollen)", a: ["hättet", "sollen"], why: "should have done = hätte + infinitive + sollen (no participle)." },
{ id: "L47-w2", lesson: 47, skill: "writing", type: "tr", topic: "Double infinitive in a subordinate clause", en: "I know that I should have apologised earlier.", hint: "use dass", de: "Ich weiß, dass ich mich früher hätte entschuldigen sollen.", alt: ["Ich weiß, dass ich mich eher hätte entschuldigen sollen."], why: "In a dass clause, hätte moves in front of the two infinitives." },

// ---------- Lesson 48: Die Zukunft der Arbeit ----------
{ id: "L48-g1", lesson: 48, skill: "grammar", topic: "da-word with sich gewöhnen an", type: "mc", q: "Unser Team hat sich schnell ___ gewöhnt, Besprechungen online abzuhalten.", opts: ["darauf", "daran", "damit", "dafür"], a: 1, why: "sich gewöhnen an → daran points forward to the zu-infinitive." },
{ id: "L48-g2", lesson: 48, skill: "grammar", topic: "Questions with wo(r)- vs. preposition + wen", type: "mc", q: "___ kann ich mich im Team wirklich verlassen? – Auf Miriam.", opts: ["Worauf", "Auf wem", "Auf wen", "Wem"], a: 2, why: "Asking about a person: preposition + wen/wem (sich verlassen auf + Akk.); wo(r)- is only for things." },
{ id: "L48-g3", lesson: 48, skill: "grammar", topic: "Discussion phrases: disagreeing", type: "mc", q: "Da bin ich anderer ___: Ich glaube nicht, dass Roboter alle Jobs ersetzen.", opts: ["Standpunkt", "Meinung", "Einwand", "Gedanke"], a: 1, why: "The fixed phrase is: Da bin ich anderer Meinung." },
{ id: "L48-v1", lesson: 48, skill: "vocab", topic: "World of work vocabulary", type: "mc", q: "Viele Betriebe suchen dringend Personal, denn der ___ wird immer größer.", opts: ["Einwand", "Fachkräftemangel", "Vortrag", "Roboter"], a: 1, why: "der Fachkräftemangel = shortage of skilled workers." },
{ id: "L48-w1", lesson: 48, skill: "writing", type: "gap", topic: "da-word with sich ärgern über", q: "Viele Mitarbeiter ärgern sich ___, dass die Software ständig abstürzt. (sich ärgern über)", a: ["darüber"], why: "über + vowel → darüber, pointing forward to the dass clause." },
{ id: "L48-w2", lesson: 48, skill: "writing", type: "tr", topic: "rechnen mit + damit, dass", en: "We expect that robots will take over many routine tasks.", hint: "use rechnen mit", de: "Wir rechnen damit, dass Roboter viele Routineaufgaben übernehmen werden.", alt: ["Wir rechnen damit, dass Roboter viele Routineaufgaben übernehmen.", "Wir rechnen damit, dass viele Routineaufgaben von Robotern übernommen werden."], why: "With a dass clause, rechnen mit needs the correlate damit." },

// ---------- Reading ----------
{ id: "L43-r1", lesson: 43, skill: "reading", type: "mc", topic: "Reading: sustainable habits", text: "Ich versuche seit einem Jahr, nachhaltiger zu leben. Auf Fleisch verzichte ich inzwischen fast ganz, und Obst und Gemüse kaufe ich auf dem Markt, auch wenn es dort etwas teurer ist als im Supermarkt. Mein Auto habe ich zwar noch, aber ich nutze es nur noch am Wochenende; zur Arbeit fahre ich mit dem Fahrrad. Schwierig ist für mich das Fliegen. Meine Eltern leben in Kanada, und obwohl ich weiß, wie hoch der CO2-Ausstoß eines Fluges ist, besuche ich sie zweimal im Jahr. Darauf möchte ich nicht verzichten. Manche Freunde finden das inkonsequent. Ich sehe das anders: Niemand ist perfekt, und jeder kleine Schritt zählt. Dennoch frage ich mich an manchen Tagen, ob meine Bemühungen überhaupt etwas bringen. Wie seht ihr das?", q: "What does the writer say about flying?", opts: ["They have stopped flying and now take the train to Canada.", "They think a flight produces hardly any CO2.", "They still fly to visit their parents twice a year, despite knowing the emissions.", "They only fly when their friends agree it is necessary."], a: 2 },
{ id: "L44-r1", lesson: 44, skill: "reading", type: "mc", topic: "Reading: a fake video", text: "Am vergangenen Wochenende tauchte auf mehreren Plattformen plötzlich ein Video auf, das angeblich einen bekannten Politiker bei einer beleidigenden Rede zeigte. Innerhalb weniger Stunden wurde es über 200.000 Mal geteilt – sogar einige seriöse Nachrichtenseiten berichteten darüber. Erst ein Faktencheck einer unabhängigen Redaktion zeigte, dass das Video mit künstlicher Intelligenz manipuliert worden war: Die Stimme passte nicht zu den Lippenbewegungen, und der Hintergrund stammte aus einem Film von 2019. Ausgerechnet die Nachrichtenseiten, die das Video verbreitet hatten, korrigierten ihre Berichte erst zwei Tage später. Bis dahin hatten zahlreiche Nutzer das Video bereits kommentiert und weiterverbreitet. Experten fordern deshalb, dass Medienkompetenz schon in der Schule vermittelt wird. „Man muss eben lernen, auch scheinbar glaubwürdige Quellen kritisch zu hinterfragen“, sagt eine Medienforscherin.", q: "How was the video shown to be fake?", opts: ["The reputable news sites noticed the fake immediately.", "An independent fact-check found it had been manipulated with AI.", "It was only shared a few times before someone noticed.", "The politician published the original speech the same day."], a: 1 },
{ id: "L45-r1", lesson: 45, skill: "reading", type: "mc", topic: "Reading: a start-up's finances", text: "Liebe Frau Klein, vielen Dank für Ihr Interesse an unserem Start-up „GrünBox“. Gern beantworte ich Ihre Fragen. Wir liefern Gemüse von Bauernhöfen aus der Region direkt an Büros in Haifa. Die Nachfrage ist im letzten Jahr deutlich gestiegen, und unser Umsatz hat sich verdoppelt. Einen Gewinn machen wir aber noch nicht, weil wir das meiste Geld in neue Kühlfahrzeuge investiert haben. Das nehmen wir bewusst in Kauf, denn wir setzen zunächst auf Wachstum. Ein Bankkredit kam für uns nicht in Frage, da die Zinsen zu hoch waren. Stattdessen suchen wir jetzt Investoren, die uns Kapital zur Verfügung stellen. Mit Ihrer Unterstützung könnten wir bis Ende des Jahres auch Tel Aviv beliefern. Gern stelle ich Ihnen unseren Businessplan bei einem persönlichen Treffen vor. Mit freundlichen Grüßen, Daniel Amar", q: "Why is GrünBox not making a profit yet?", opts: ["Demand for its vegetables has fallen.", "It has to pay back a large bank loan.", "Its turnover has stayed the same for a year.", "It has invested most of its money in new refrigerated vehicles."], a: 3 },
{ id: "L47-r1", lesson: 47, skill: "reading", type: "mc", topic: "Reading: a missed opportunity", text: "Vor drei Jahren hatte ich die Gelegenheit, für ein Jahr in Wien zu arbeiten. Meine Firma hätte mir sogar die Wohnung bezahlt. Aber ich hatte Angst, meine Freunde und meine Familie zu verlassen, und habe abgelehnt. Heute bereue ich das. Ich hätte den Mut haben sollen, einfach Ja zu sagen. Meine Kollegin Noa hat die Stelle damals genommen, und wenn sie heute von Wien erzählt, klingt es, als ob es das beste Jahr ihres Lebens gewesen wäre. Manchmal tue ich so, als wäre mir das gleichgültig, aber ehrlich gesagt bin ich ein bisschen neidisch. Meine Mutter meint, wer immer nur zurückschaut, der verpasst die Chancen von heute. Im Großen und Ganzen hat sie wohl recht. Nächstes Jahr bewerbe ich mich deshalb auf ein Programm in Berlin.", q: "How does the writer really feel about Noa's year in Vienna?", opts: ["Completely indifferent, because they never wanted to go abroad.", "A bit envious, although they sometimes pretend not to care.", "Glad, because Noa had a difficult year there.", "Angry, because their company refused to pay for a flat."], a: 1 },

// ---------- Listening ----------
{ id: "L43-l1", lesson: 43, skill: "listening", type: "mc", topic: "Listening: sustainable habits", audio: "Auch wenn Fliegen schlecht für das Klima ist, würde ich nicht darauf verzichten, Freunde in Europa zu besuchen.", q: "What does the speaker say about flying?", opts: ["They have stopped flying to Europe for the climate.", "They think flying is not really bad for the climate.", "They would keep flying to visit friends in Europe, despite the climate impact.", "They would rather their friends visited them instead."], a: 2 },
{ id: "L46-l1", lesson: 46, skill: "listening", type: "mc", topic: "Listening: at the theatre", audio: "Das Publikum hat minutenlang applaudiert, was hier selten vorkommt.", q: "What happened?", opts: ["The audience applauded for minutes, which rarely happens here.", "Few people came, which is unusual here.", "The applause was short, as it usually is here.", "The audience left after a few minutes."], a: 0 },
{ id: "L48-l1", lesson: 48, skill: "listening", type: "mc", topic: "Listening: giving presentations", audio: "Ich achte vor allem darauf, dass meine Folien übersichtlich sind und ich möglichst frei spreche.", q: "What does the speaker pay most attention to?", opts: ["Using as many slides as possible", "Reading the text exactly from the slides", "Keeping the talk under twenty minutes", "Clear slides and speaking as freely as possible"], a: 3 },
{ id: "L45-l1", lesson: 45, skill: "listening", type: "dict", topic: "Dictation: zur Verfügung stellen", audio: "Die Firma stellt allen Mitarbeitern ein Diensthandy zur Verfügung.", q: "Die Firma stellt ___ Mitarbeitern ein Diensthandy zur Verfügung.", a: ["allen"] },
{ id: "L47-l1", lesson: 47, skill: "listening", type: "dict", topic: "Dictation: Konjunktiv II past", audio: "Wenn ich das gewusst hätte, wäre ich natürlich gekommen.", q: "Wenn ich das gewusst hätte, ___ ich natürlich gekommen.", a: ["wäre"] }
);
