// Pronunciation trainer: the German sounds English and Hebrew speakers find hardest.
// `match` finds the sound inside any word, so feedback on a missed word can point to the right tip.
const SOUNDS = [
  { id: "ue", label: "ü", title: "The ü sound",
    how: "Say a long \"ee\" (as in see). Keep your tongue exactly there and round your lips tightly, as if to whistle. Don't let it slide into \"oo\".",
    match: /ü|^typ/i, words: ["fünf", "über", "Tür", "müde", "Brüder", "Küche"],
    pairs: [["Mutter", "Mütter"], ["Bruder", "Brüder"], ["Kuchen", "Küchen"], ["vier", "für"]] },
  { id: "oe", label: "ö", title: "The ö sound",
    how: "Say \"e\" as in bed (short) or \"ay\" (long). Keep your tongue still and round your lips as for \"o\". It's the sound in British \"bird\" with rounded lips.",
    match: /ö/i, words: ["schön", "hören", "Größe", "möchten", "zwölf", "Söhne"],
    pairs: [["schon", "schön"], ["Ofen", "Öfen"], ["lesen", "lösen"]] },
  { id: "ae", label: "ä", title: "The ä sound",
    how: "Short ä is the \"e\" in bed. Long ä is like \"air\" without the r. It is never the English \"a\" in cat.",
    match: /ä(?!u)/i, words: ["Äpfel", "Käse", "Mädchen", "spät", "Bäder", "Länder"],
    pairs: [["Apfel", "Äpfel"], ["Vater", "Väter"], ["Mann", "Männer"]] },
  { id: "ich", label: "ich", title: "The soft ch (ich)",
    how: "After e, i, ä, ö, ü, ei, eu and consonants, ch is a soft hiss. Say the \"h\" in huge and push more air, tongue high near the roof of your mouth. Not \"sh\", not \"k\". A final -ig sounds the same: zwanzig = \"zwanzich\".",
    match: /([eiäöüylnr]ch)|ig$/i, words: ["ich", "nicht", "Milch", "sprechen", "möchten", "zwanzig"],
    pairs: [["mich", "misch"], ["Kirche", "Kirsche"], ["dich", "dick"]] },
  { id: "ach", label: "ach", title: "The hard ch (ach)",
    how: "After a, o, u and au, ch is made at the back of the throat, a light rasp like Scottish \"loch\" or Hebrew ח. Keep air flowing; don't stop it like a \"k\".",
    match: /(a|o|u|au)ch/i, words: ["acht", "Nacht", "Buch", "Kuchen", "auch", "Tochter"],
    pairs: [["Nacht", "nackt"], ["Buch", "Bug"]] },
  { id: "r", label: "r", title: "The German R",
    how: "At the start of a syllable the R is made at the back, a soft gargle at the uvula (close to Hebrew ר), never the English r. At the end of a word -er turns into a short \"uh\": Vater = \"fah-tuh\", hier = \"hee-uh\".",
    match: /r/i, words: ["rot", "Brot", "drei", "Straße", "Vater", "Wasser"],
    pairs: [["Rat", "Grad"], ["Mutter", "Mut"]] },
  { id: "z", label: "z", title: "Z is ts",
    how: "Z is always \"ts\", even at the start of a word: zehn = \"tsehn\". The same goes for tz.",
    match: /z/i, words: ["zehn", "zwei", "Zimmer", "Zug", "Zeit", "jetzt"],
    pairs: [["Zeit", "seit"], ["Zoo", "so"]] },
  { id: "wv", label: "w / v", title: "W sounds like v, V like f",
    how: "German w is the English v: Wasser = \"vasser\". German v is usually an f: Vater = \"fater\", vier = \"feer\".",
    match: /w|v/i, words: ["Wasser", "wohnen", "wie", "Vater", "vier", "viel"],
    pairs: [["wir", "vier"], ["Wein", "fein"]] },
  { id: "ei", label: "ei / ie", title: "ei versus ie",
    how: "Read the second letter. ei sounds like English \"eye\": drei, mein. ie is a long \"ee\": vier, sie.",
    match: /ei|ie|ai/i, words: ["drei", "heißen", "Wein", "vier", "Bier", "Liebe"],
    pairs: [["Wein", "Wien"], ["leider", "Lieder"]] },
  { id: "eu", label: "eu / äu", title: "eu and äu",
    how: "Both sound like \"oy\" in boy: neun = \"noyn\", Häuser = \"hoyzer\".",
    match: /eu|äu/i, words: ["neun", "heute", "Freund", "Häuser", "teuer", "Deutsch"],
    pairs: [["neun", "nein"]] },
  { id: "sch", label: "sch / sp / st", title: "sch, sp and st",
    how: "sch is \"sh\". At the start of a word or word part, sp sounds \"shp\" and st sounds \"sht\": Sprache = \"shprache\", aufstehen = \"auf-shtehen\".",
    match: /sch|^sp|^st|(auf|an|ver|be)st/i, words: ["Schule", "schön", "sprechen", "Stadt", "Straße", "aufstehen"],
    pairs: [["Stadt", "Schatz"], ["Fest", "Fisch"]] },
  { id: "s", label: "s / ß", title: "Soft s and sharp ß",
    how: "s before a vowel buzzes like English \"z\": Sonne = \"zonne\", sieben = \"zeeben\". ß and ss are always a sharp \"s\".",
    match: /^s[aeiouäöü]|ß|ss/i, words: ["Sonne", "sieben", "Saft", "heißen", "Straße", "Wasser"],
    pairs: [["reisen", "reißen"], ["Rose", "Rosse"]] },
  { id: "end", label: "-b -d -g", title: "Hard endings",
    how: "At the end of a word or syllable b, d and g harden to p, t and k: Tag = \"tahk\", Kind = \"kint\", gelb = \"gelp\".",
    match: /[bdg]$/i, words: ["Tag", "Kind", "Hand", "gelb", "Abend", "Geld"],
    pairs: [["Rad", "Rat"], ["Bund", "bunt"]] },
  { id: "len", label: "long / short", title: "Long and short vowels",
    how: "Vowel length changes meaning. Before a double consonant the vowel is short and clipped (Bett). Before h, a doubled vowel or a single consonant it is often long (Beet, Ofen).",
    match: /(aa|ee|oo|ah|eh|ih|oh|uh)|(bb|dd|ff|gg|kk|ll|mm|nn|pp|rr|ss|tt|ck)/i, words: ["Stadt", "Staat", "Bett", "Beet", "Zimmer", "Ofen"],
    pairs: [["Stadt", "Staat"], ["Bett", "Beet"], ["offen", "Ofen"], ["Kamm", "kam"]] }
];
